"""Write every _sync twin from its _async source, or with --check fail when a committed twin drifted."""

from __future__ import annotations

import argparse
import io
import itertools
import subprocess
import sys
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAIRS = [ROOT / "src" / "useshards", ROOT / "suite"]
# These twins are written by hand, since threads and asyncio differ in more than the keywords.
HANDWRITTEN = {"_backend.py", "mode.py"}
HEADER = "# Generated by scripts/unasync.py from {source}. Edit that file, not this one.\n"
NAMES = {
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    "__aiter__": "__iter__",
    "__anext__": "__next__",
    "aclose": "close",
    "aiter_bytes": "iter_bytes",
    "aiter_lines": "iter_lines",
    "aread": "read",
    "asynccontextmanager": "contextmanager",
    "asyncio_detailed": "sync_detailed",
    "set_async_httpx_client": "set_httpx_client",
    "StopAsyncIteration": "StopIteration",
    "_async": "_sync",
}


def unasync(source: str) -> str:
    lines = source.splitlines(keepends=True)
    starts = [0]
    for line in lines:
        starts.append(starts[-1] + len(line))
    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    edits: list[tuple[int, int, str]] = []
    for token, following in itertools.pairwise(tokens):
        if token.type != tokenize.NAME:
            continue
        start = starts[token.start[0] - 1] + token.start[1]
        end = starts[token.end[0] - 1] + token.end[1]
        if token.string in ("async", "await"):
            edits.append((start, starts[following.start[0] - 1] + following.start[1], ""))
            continue
        renamed = _renamed(token.string)
        if renamed != token.string:
            edits.append((start, end, renamed))
    out = source
    for start, end, text in reversed(edits):
        out = out[:start] + text + out[end:]
    return out


def _renamed(name: str) -> str:
    if name in NAMES:
        return NAMES[name]
    if name.startswith("Async") and name[5:6].isupper():
        return name[5:]
    return name


def twins() -> dict[Path, str]:
    """Every generated twin and the text it must hold."""
    out: dict[Path, str] = {}
    for base in PAIRS:
        for source in sorted((base / "_async").rglob("*.py")):
            if source.name in HANDWRITTEN:
                continue
            target = base / "_sync" / source.relative_to(base / "_async")
            text = HEADER.format(source=source.relative_to(ROOT).as_posix()) + unasync(source.read_text())
            out[target] = _formatted(text, target)
    return out


def _formatted(text: str, target: Path) -> str:
    """Sort the imports the renames moved, then format, as the committed twin was."""
    for args in (["check", "--fix", "--select", "I", "--quiet"], ["format", "--quiet"]):
        done = subprocess.run(
            [sys.executable, "-m", "ruff", *args, "--stdin-filename", str(target), "-"],
            input=text,
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
        if done.returncode != 0:
            raise SystemExit(f"ruff {args[0]} on {target.relative_to(ROOT)}: {done.stderr.strip()}")
        text = done.stdout
    return text


def strays(want: dict[Path, str]) -> list[Path]:
    """Generated files under a _sync tree whose _async source is gone."""
    found = []
    for base in PAIRS:
        for path in sorted((base / "_sync").rglob("*.py")):
            if path not in want and path.name not in HANDWRITTEN:
                found.append(path)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when a committed twin differs from its source")
    check = parser.parse_args().check
    want = twins()
    drifted = [path for path, text in want.items() if not path.exists() or path.read_text() != text]
    extra = strays(want)
    if check:
        for path in drifted:
            print(f"unasync: {path.relative_to(ROOT)} differs from its _async source", file=sys.stderr)
        for path in extra:
            print(f"unasync: {path.relative_to(ROOT)} has no _async source", file=sys.stderr)
        if drifted or extra:
            print("unasync: run make sdk-py and commit the result", file=sys.stderr)
            return 1
        return 0
    for path in drifted:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want[path])
    for path in extra:
        path.unlink()
    return 0


if __name__ == "__main__":
    sys.exit(main())
