package serve

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

const testToken = "e2e-token-value"

// upstream is a fake daemon on a socket under a root, which counts what reached it.
type upstream struct {
	root     string
	dialed   *atomic.Int64
	requests chan string
}

// fakeDaemon answers every request with 200 and its own body, and counts the connections it accepted.
func fakeDaemon(t *testing.T) *upstream {
	t.Helper()

	root := shortRoot(t)
	up := &upstream{root: root, dialed: &atomic.Int64{}, requests: make(chan string, 8)}

	listener, err := net.Listen("unix", filepath.Join(root, "shard.sock"))
	if err != nil {
		t.Fatalf("listen on the fake socket: %v", err)
	}
	t.Cleanup(func() { listener.Close() })

	server := &http.Server{
		ReadHeaderTimeout: time.Second,
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			select {
			case up.requests <- r.Method + " " + r.URL.Path + " auth=" + r.Header.Get("Authorization"):
			default:
			}
			fmt.Fprintln(w, `{"sandboxes":[]}`)
		}),
	}
	server.ConnState = func(_ net.Conn, state http.ConnState) {
		if state == http.StateNew {
			up.dialed.Add(1)
		}
	}

	go server.Serve(listener)
	t.Cleanup(func() { server.Close() })

	return up
}

// front starts a server over the fake daemon and answers the address it bound.
func front(t *testing.T, root, tokenFile string) string {
	t.Helper()

	cert, key := keyPair(t)

	server, err := New(Config{Listen: "127.0.0.1:0", CertFile: cert, KeyFile: key, TokenFile: tokenFile, Root: root, Out: io.Discard})
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	listener, err := server.Listen()
	if err != nil {
		t.Fatalf("Listen: %v", err)
	}

	ctx, cancel := context.WithCancel(t.Context())
	ended := make(chan error, 1)
	go func() { ended <- server.Serve(ctx, listener) }()

	t.Cleanup(func() {
		cancel()
		if err := <-ended; err != nil {
			t.Errorf("the front ended with %v", err)
		}
	})

	return listener.Addr().String()
}

// ask sends one request to the front over TLS, with the bearer token when it is not empty.
func ask(t *testing.T, address, token string) *http.Response {
	t.Helper()

	client := &http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{
		InsecureSkipVerify: true, //nolint:gosec // G402: the certificate is generated by this test
	}}}

	req, err := http.NewRequestWithContext(t.Context(), http.MethodGet, "https://"+address+"/v0/sandboxes", nil)
	if err != nil {
		t.Fatalf("build the request: %v", err)
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("ask the front: %v", err)
	}
	t.Cleanup(func() { resp.Body.Close() })

	return resp
}

func TestTheFrontSplicesAnAuthorizedRequestOntoTheSocket(t *testing.T) {
	up := fakeDaemon(t)

	resp := ask(t, front(t, up.root, tokenFile(t, testToken)), testToken) //nolint:bodyclose // ask closes the body in a cleanup

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("the front answered %d, want 200", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read the answer: %v", err)
	}
	if got := strings.TrimSpace(string(body)); got != `{"sandboxes":[]}` {
		t.Errorf("the front answered %q, want what the daemon wrote", got)
	}

	select {
	case got := <-up.requests:
		// The head is replayed byte for byte, so the daemon sees the request the client wrote.
		if want := "GET /v0/sandboxes auth=Bearer " + testToken; got != want {
			t.Errorf("the daemon saw %q, want %q", got, want)
		}
	default:
		t.Error("the daemon saw no request")
	}
}

func TestABadTokenIs401AndNothingIsDialed(t *testing.T) {
	up := fakeDaemon(t)
	address := front(t, up.root, tokenFile(t, testToken))

	for _, token := range []string{"", "wrong-token-value", testToken + "x"} {
		resp := ask(t, address, token) //nolint:bodyclose // ask closes the body in a cleanup
		if resp.StatusCode != http.StatusUnauthorized {
			t.Errorf("the token %q answered %d, want 401", token, resp.StatusCode)
		}
	}

	if dialed := up.dialed.Load(); dialed != 0 {
		t.Errorf("the front dialed the socket %d times for a request it refused, want none", dialed)
	}
}

func TestTheFrontRefusesToStartWithoutATLSPair(t *testing.T) {
	cert, key := keyPair(t)
	token := tokenFile(t, testToken)
	root := shortRoot(t)

	for name, cfg := range map[string]Config{
		"no certificate": {KeyFile: key, TokenFile: token, Root: root},
		"no key":         {CertFile: cert, TokenFile: token, Root: root},
		"neither":        {TokenFile: token, Root: root},
	} {
		if _, err := New(cfg); err == nil {
			t.Errorf("%s: the front started, want a refusal", name)
		}
	}
}

func TestReadTokenRefusesAFileTheHostCanRead(t *testing.T) {
	path := tokenFile(t, testToken)
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	_, err := ReadToken(path)
	if err == nil {
		t.Fatal("a world-readable token file was accepted")
	}
	if strings.Contains(err.Error(), testToken) {
		t.Error("the refusal carries the token value")
	}
}

func TestReadTokenRefusesAnEmptyFileAndNoFile(t *testing.T) {
	if _, err := ReadToken(tokenFile(t, "  \n")); err == nil {
		t.Error("an empty token file was accepted")
	}
	if _, err := ReadToken(""); err == nil {
		t.Error("no token file at all was accepted")
	}
}

func TestReadTokenTrimsTheFile(t *testing.T) {
	token, err := ReadToken(tokenFile(t, testToken+"\n"))
	if err != nil {
		t.Fatalf("ReadToken: %v", err)
	}
	if token != testToken {
		t.Errorf("ReadToken answered %q, want the trimmed token", token)
	}
}

func tokenFile(t *testing.T, value string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "token")
	if err := os.WriteFile(path, []byte(value), 0o600); err != nil {
		t.Fatalf("write the token file: %v", err)
	}

	return path
}

// shortRoot keeps a unix socket path under the 104 bytes macOS allows.
func shortRoot(t *testing.T) string {
	t.Helper()

	root, err := os.MkdirTemp("", "shard") //nolint:usetesting // t.TempDir is too long for a socket path
	if err != nil {
		t.Fatalf("make a root: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(root) })

	return root
}

// keyPair writes a self-signed certificate for 127.0.0.1 and answers the two paths.
func keyPair(t *testing.T) (string, string) {
	t.Helper()

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generate a key: %v", err)
	}

	template := x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "localhost"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IsCA:         true,
	}

	der, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		t.Fatalf("sign the certificate: %v", err)
	}

	marshalled, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		t.Fatalf("marshal the key: %v", err)
	}

	dir := t.TempDir()
	certPath, keyPath := filepath.Join(dir, "cert.pem"), filepath.Join(dir, "key.pem")

	if err := os.WriteFile(certPath, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o600); err != nil {
		t.Fatalf("write the certificate: %v", err)
	}
	if err := os.WriteFile(keyPath, pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: marshalled}), 0o600); err != nil {
		t.Fatalf("write the key: %v", err)
	}

	return certPath, keyPath
}
