package serve

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/coder/websocket"
	"github.com/golang-jwt/jwt/v5"

	"github.com/presmihaylov/shard/models"
	"github.com/presmihaylov/shard/services/api"
)

const testSecret = "e2e-secret-value-0000000000000000"

// upstream is a fake daemon on a socket under a root, which counts what reached it.
type upstream struct {
	root     string
	dialed   *atomic.Int64
	requests chan string
}

// fakeDaemon answers every request with 200 and its own body, echoes on a WebSocket, and counts the connections it accepted.
func fakeDaemon(t *testing.T) *upstream {
	return daemon(t, true)
}

// plainDaemon answers every request with 200, even a WebSocket handshake, so the front's non-101 path is exercised.
func plainDaemon(t *testing.T) *upstream {
	return daemon(t, false)
}

// daemon starts a fake daemon on a socket under a root and counts what reaches it. When upgrade is true it answers a WebSocket handshake with 101 and echoes; when false it answers every request with 200.
func daemon(t *testing.T, upgrade bool) *upstream {
	t.Helper()

	root := shortRoot(t)
	up := &upstream{root: root, dialed: &atomic.Int64{}, requests: make(chan string, 8)}

	listener, err := net.Listen("unix", filepath.Join(root, "shard.sock"))
	if err != nil {
		t.Fatalf("listen on the fake socket: %v", err)
	}
	t.Cleanup(func() { listener.Close() })

	server := &http.Server{
		ReadHeaderTimeout: time.Second,
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			select {
			case up.requests <- r.Method + " " + r.URL.Path + " auth=" + r.Header.Get("Authorization"):
			default:
			}
			if upgrade && r.Header.Get("Upgrade") == "websocket" {
				echo(t, w, r)

				return
			}
			fmt.Fprintln(w, `{"sandboxes":[]}`)
		}),
	}
	server.ConnState = func(_ net.Conn, state http.ConnState) {
		if state == http.StateNew {
			up.dialed.Add(1)
		}
	}

	go server.Serve(listener)
	t.Cleanup(func() { server.Close() })

	return up
}

// echo answers a WebSocket handshake and sends one message back as it came, then closes as the daemon does.
func echo(t *testing.T, w http.ResponseWriter, r *http.Request) {
	t.Helper()

	conn, err := websocket.Accept(w, r, nil)
	if err != nil {
		t.Errorf("accept the WebSocket: %v", err)

		return
	}
	defer conn.CloseNow()

	kind, payload, err := conn.Read(r.Context())
	if err != nil {
		t.Errorf("read the message: %v", err)

		return
	}
	if err := conn.Write(r.Context(), kind, payload); err != nil {
		t.Errorf("echo the message: %v", err)

		return
	}
	if err := conn.Close(websocket.StatusNormalClosure, "echoed"); err != nil {
		t.Errorf("close the WebSocket: %v", err)
	}
}

// front starts a server over the fake daemon and answers the address it bound.
func front(t *testing.T, root, secret string) string {
	t.Helper()

	cert, key := keyPair(t)

	server, err := New(Config{Listen: "127.0.0.1:0", CertFile: cert, KeyFile: key, SecretFile: secret, Root: root, Out: io.Discard})
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	listener, err := server.Listen()
	if err != nil {
		t.Fatalf("Listen: %v", err)
	}

	ctx, cancel := context.WithCancel(t.Context())
	ended := make(chan error, 1)
	go func() { ended <- server.Serve(ctx, listener) }()

	t.Cleanup(func() {
		cancel()
		if err := <-ended; err != nil {
			t.Errorf("the front ended with %v", err)
		}
	})

	return listener.Addr().String()
}

// trusting speaks TLS to a front whose certificate this test made.
func trusting() *http.Client {
	return &http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{
		InsecureSkipVerify: true, //nolint:gosec // G402: the certificate is generated by this test
	}}}
}

// ask sends one request to the front over TLS, with the bearer token when it is not empty.
func ask(t *testing.T, address, token string) *http.Response {
	t.Helper()

	client := trusting()

	req, err := http.NewRequestWithContext(t.Context(), http.MethodGet, "https://"+address+"/v0/sandboxes", nil)
	if err != nil {
		t.Fatalf("build the request: %v", err)
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("ask the front: %v", err)
	}
	t.Cleanup(func() { resp.Body.Close() })

	return resp
}

// askRoute sends one request of method to path on the front over TLS, with the bearer token when it is not empty.
func askRoute(t *testing.T, address, token, method, path string) *http.Response {
	t.Helper()

	req, err := http.NewRequestWithContext(t.Context(), method, "https://"+address+path, nil)
	if err != nil {
		t.Fatalf("build the request: %v", err)
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	resp, err := trusting().Do(req)
	if err != nil {
		t.Fatalf("ask the front: %v", err)
	}
	t.Cleanup(func() { resp.Body.Close() })

	return resp
}

// drain collects what a channel holds, gives a late sender a short moment, and answers the list.
func drain(ch chan string) []string {
	var got []string
	for {
		select {
		case s := <-ch:
			got = append(got, s)
		case <-time.After(200 * time.Millisecond):
			return got
		}
	}
}

func TestTheFrontSplicesAnAuthorizedRequestOntoTheSocket(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	token := mint(t, env, "ci")

	resp := ask(t, front(t, up.root, env.secret), token) //nolint:bodyclose // ask closes the body in a cleanup

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("the front answered %d, want 200", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read the answer: %v", err)
	}
	if got := strings.TrimSpace(string(body)); got != `{"sandboxes":[]}` {
		t.Errorf("the front answered %q, want what the daemon wrote", got)
	}

	select {
	case got := <-up.requests:
		// The front rewrites only the Connection header, so the method, the path and the token reach the daemon.
		if want := "GET /v0/sandboxes auth=Bearer " + token; got != want {
			t.Errorf("the daemon saw %q, want %q", got, want)
		}
	default:
		t.Error("the daemon saw no request")
	}
}

// The front carries every message of a WebSocket both ways, because it stops parsing at the head.
func TestTheFrontSplicesAWebSocket(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)
	token := mint(t, env, "ci")

	header := http.Header{"Authorization": {"Bearer " + token}}
	conn, _, err := websocket.Dial(t.Context(), "wss://"+address+"/v0/sandboxes/sandbox1/logs?follow=true", &websocket.DialOptions{HTTPClient: trusting(), HTTPHeader: header}) //nolint:bodyclose // a 101 has no body to close
	if err != nil {
		t.Fatalf("dial through the front: %v", err)
	}
	defer conn.CloseNow()

	if err := conn.Write(t.Context(), websocket.MessageBinary, []byte{1, 'u', 'p'}); err != nil {
		t.Fatalf("write through the front: %v", err)
	}

	kind, payload, err := conn.Read(t.Context())
	if err != nil {
		t.Fatalf("read through the front: %v", err)
	}
	if kind != websocket.MessageBinary || string(payload) != "\x01up" {
		t.Errorf("the echo came back as %v %q", kind, payload)
	}

	var closed websocket.CloseError
	if _, _, err := conn.Read(t.Context()); !errors.As(err, &closed) || closed.Code != websocket.StatusNormalClosure || closed.Reason != "echoed" {
		t.Errorf("the session ended with %v, want the daemon's close 1000 with its reason", err)
	}

	_, _, err = websocket.Dial(t.Context(), "wss://"+address+"/v0/sandboxes/sandbox1/logs?follow=true", &websocket.DialOptions{HTTPClient: trusting()}) //nolint:bodyclose // a refused dial has no body to close
	if err == nil || !strings.Contains(err.Error(), "401") {
		t.Errorf("a dial with no token got %v, want the 401 of the front", err)
	}
}

func TestABadTokenIs401AndNothingIsDialed(t *testing.T) {
	up := fakeDaemon(t)
	address := front(t, up.root, secretFile(t, testSecret))

	now := time.Now()
	valid := jwt.RegisteredClaims{Subject: "ci", IssuedAt: jwt.NewNumericDate(now), ExpiresAt: jwt.NewNumericDate(now.Add(time.Hour))}

	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("generate an rsa key: %v", err)
	}

	tokens := map[string]string{
		"empty":        "",
		"not a jwt":    "not-a-jwt",
		"wrong secret": signed(t, jwt.SigningMethodHS256, []byte("another-secret-value-000000000000"), valid),
		"alg none":     signed(t, jwt.SigningMethodNone, jwt.UnsafeAllowNoneSignatureType, valid),
		"alg rs256":    signed(t, jwt.SigningMethodRS256, rsaKey, valid),
		"expired":      signed(t, jwt.SigningMethodHS256, []byte(testSecret), jwt.RegisteredClaims{Subject: "ci", IssuedAt: jwt.NewNumericDate(now.Add(-2 * time.Hour)), ExpiresAt: jwt.NewNumericDate(now.Add(-time.Hour))}),
		"no subject":   signed(t, jwt.SigningMethodHS256, []byte(testSecret), jwt.RegisteredClaims{IssuedAt: jwt.NewNumericDate(now), ExpiresAt: jwt.NewNumericDate(now.Add(time.Hour))}),
		"no expiry":    signed(t, jwt.SigningMethodHS256, []byte(testSecret), jwt.RegisteredClaims{Subject: "ci", IssuedAt: jwt.NewNumericDate(now)}),
	}

	for name, token := range tokens {
		resp := ask(t, address, token) //nolint:bodyclose // ask closes the body in a cleanup
		if resp.StatusCode != http.StatusUnauthorized {
			t.Errorf("%s: the front answered %d, want 401", name, resp.StatusCode)
		}

		var body struct {
			Error struct {
				Code    models.Code `json:"code"`
				Message string      `json:"message"`
			} `json:"error"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
			t.Fatalf("%s: decode the refusal: %v", name, err)
		}
		if body.Error.Code != models.CodeUnauthorized || body.Error.Message == "" {
			t.Errorf("%s: the refusal reads %+v, want a line and the code unauthorized", name, body)
		}
	}

	if dialed := up.dialed.Load(); dialed != 0 {
		t.Errorf("the front dialed the socket %d times for requests it refused, want none", dialed)
	}
}

func TestTheFrontRefusesToStartWithoutATLSPair(t *testing.T) {
	cert, key := keyPair(t)
	secret := secretFile(t, testSecret)
	root := shortRoot(t)

	for name, cfg := range map[string]Config{
		"no certificate": {KeyFile: key, SecretFile: secret, Root: root},
		"no key":         {CertFile: cert, SecretFile: secret, Root: root},
		"neither":        {SecretFile: secret, Root: root},
	} {
		if _, err := New(cfg); err == nil {
			t.Errorf("%s: the front started, want a refusal", name)
		}
	}
}

func TestTheFrontRefusesToStartWithoutASecret(t *testing.T) {
	cert, key := keyPair(t)
	if _, err := New(Config{CertFile: cert, KeyFile: key, Root: shortRoot(t)}); err == nil {
		t.Error("the front started with no secret file, want a refusal")
	}
}

func TestMintAndVerifyRoundTrip(t *testing.T) {
	token, err := Mint([]byte(testSecret), "ci", []string{"sandbox:read", "exec"}, time.Hour)
	if err != nil {
		t.Fatalf("Mint: %v", err)
	}

	sub, scopes, _, err := verify([]byte(testSecret), token)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if sub != "ci" {
		t.Errorf("verify answered %q, want the subject the token names", sub)
	}
	if strings.Join(scopes, ",") != "sandbox:read,exec" {
		t.Errorf("verify answered scopes %v, want the ones the token carries", scopes)
	}
}

func TestMintDefaultsToTheEveryVerbScope(t *testing.T) {
	token, err := Mint([]byte(testSecret), "ci", nil, time.Hour)
	if err != nil {
		t.Fatalf("Mint: %v", err)
	}

	_, scopes, _, err := verify([]byte(testSecret), token)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if strings.Join(scopes, ",") != "*" {
		t.Errorf("verify answered scopes %v, want the default [\"*\"] Mint writes", scopes)
	}
}

// A token minted before SHARD-195 carries no scopes claim; the front still reads it as every verb.
func TestVerifyReadsAnAbsentScopesClaimAsEveryVerb(t *testing.T) {
	now := time.Now()
	token := signed(t, jwt.SigningMethodHS256, []byte(testSecret),
		jwt.RegisteredClaims{ID: "a-token-id", Subject: "ci", IssuedAt: jwt.NewNumericDate(now), ExpiresAt: jwt.NewNumericDate(now.Add(time.Hour))})

	_, scopes, _, err := verify([]byte(testSecret), token)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if len(scopes) != 0 {
		t.Errorf("verify answered scopes %v, want none, which is every verb", scopes)
	}
}

func TestMintRefusesAnEmptySubjectAndANegativeDuration(t *testing.T) {
	if _, err := Mint([]byte(testSecret), "", nil, time.Hour); err == nil {
		t.Error("Mint signed a token with no subject")
	}
	if _, err := Mint([]byte(testSecret), "ci", nil, -time.Hour); err == nil {
		t.Error("Mint signed a token with a negative duration")
	}
	// A duration of zero is valid now: it mints a token that never expires.
	if _, err := Mint([]byte(testSecret), "ci", nil, 0); err != nil {
		t.Errorf("Mint refused a zero duration, which should mint a token that never expires: %v", err)
	}
}

// MintToken's record carries the scopes asked and an expires_at equal to the token's exp, to the second.
func TestMintTokenRecordAgreesWithTheToken(t *testing.T) {
	minted, err := MintToken([]byte(testSecret), "ci", []string{"sandbox:read"}, time.Hour)
	if err != nil {
		t.Fatalf("MintToken: %v", err)
	}
	if strings.Join(minted.Scopes, ",") != "sandbox:read" {
		t.Errorf("the record carries scopes %v, want the ones asked", minted.Scopes)
	}
	if minted.ExpiresAt == nil {
		t.Fatal("the record carries no expires_at")
	}
	if minted.ExpiresAt.Location() != time.UTC {
		t.Errorf("the record expires_at %s is not in UTC", minted.ExpiresAt)
	}

	var c claims
	if _, err := jwt.ParseWithClaims(minted.Token, &c, func(*jwt.Token) (any, error) { return []byte(testSecret), nil },
		jwt.WithValidMethods([]string{"HS256"})); err != nil {
		t.Fatalf("parse the minted token: %v", err)
	}
	if minted.ExpiresAt.Unix() != c.ExpiresAt.Unix() {
		t.Errorf("the record expires_at %d does not equal the token exp %d", minted.ExpiresAt.Unix(), c.ExpiresAt.Unix())
	}
}

// With no scopes MintToken defaults to ["*"] and writes it into the token, so the record and token agree.
func TestMintTokenDefaultsAndWritesTheScopesClaim(t *testing.T) {
	minted, err := MintToken([]byte(testSecret), "ci", nil, time.Hour)
	if err != nil {
		t.Fatalf("MintToken: %v", err)
	}
	if strings.Join(minted.Scopes, ",") != "*" {
		t.Errorf("the record carries scopes %v, want [\"*\"] by default", minted.Scopes)
	}

	_, scopes, _, err := verify([]byte(testSecret), minted.Token)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if strings.Join(scopes, ",") != "*" {
		t.Errorf("the token carries scopes %v, want the written default [\"*\"]", scopes)
	}
}

// ReadToken takes the mint record whole or a bare token, and refuses a broken record.
func TestReadTokenAcceptsTheRecordOrTheBareToken(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) string {
		t.Helper()
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
		return p
	}

	for name, path := range map[string]string{
		"a bare token": write("bare", "  the.jwt.value\n"),
		"a record":     write("record", `{"token":"the.jwt.value","expires_at":null,"scopes":["*"]}`+"\n"),
	} {
		got, err := ReadToken(path)
		if err != nil {
			t.Fatalf("%s: ReadToken: %v", name, err)
		}
		if got != "the.jwt.value" {
			t.Errorf("%s: ReadToken answered %q, want the token", name, got)
		}
	}

	if _, err := ReadToken(write("broken", "{not json")); err == nil {
		t.Error("ReadToken accepted a broken record")
	}
	if _, err := ReadToken(write("no token", `{"scopes":["*"]}`)); err == nil {
		t.Error("ReadToken accepted a record with no token")
	}
}

func TestSetConnectionCloseForcesConnectionClose(t *testing.T) {
	head := []byte("GET /v0/sandboxes HTTP/1.1\r\nHost: box\r\nConnection: keep-alive\r\n\r\n")

	got := string(setConnectionClose(head))
	if strings.Count(strings.ToLower(got), "connection:") != 1 {
		t.Errorf("the forwarded head is %q, want exactly one Connection header", got)
	}
	if !strings.Contains(got, "Connection: close\r\n") {
		t.Errorf("the forwarded head is %q, want Connection: close", got)
	}
	if strings.Contains(strings.ToLower(got), "keep-alive") {
		t.Errorf("the forwarded head is %q, want the client's Connection dropped", got)
	}
	if !strings.HasPrefix(got, "GET /v0/sandboxes HTTP/1.1\r\n") {
		t.Errorf("the forwarded head lost the request line: %q", got)
	}
	if !strings.HasSuffix(got, "\r\n\r\n") {
		t.Errorf("the forwarded head does not end the headers: %q", got)
	}
}

// A lone Upgrade header is not a handshake: without all four headers the front must force Connection: close.
func TestIsHandshakeNeedsAllFourHeaders(t *testing.T) {
	full := "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nHost: box\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n"
	if !isHandshake([]byte(full)) {
		t.Error("a full four-header handshake was not recognized")
	}

	for name, head := range map[string]string{
		"no key":        "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\n\r\n",
		"no version":    "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n",
		"no upgrade":    "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n",
		"no connection": "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n",
		"wrong version": "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 8\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n",
		"plain request": "GET /v0/sandboxes HTTP/1.1\r\nHost: box\r\n\r\n",
	} {
		if isHandshake([]byte(head)) {
			t.Errorf("%s: a partial upgrade was treated as a handshake", name)
		}
	}
}

// A sandbox:read token lists and inspects, and is 403 on every route it does not name; a forbidden route is never dialed.
func TestAScopedTokenReachesOnlyItsRoutes(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)
	token := mintScoped(t, env, "reader", "sandbox:read")

	if resp := askRoute(t, address, token, http.MethodGet, "/v0/sandboxes"); resp.StatusCode != http.StatusOK { //nolint:bodyclose // askRoute closes the body in a cleanup
		t.Errorf("a sandbox:read token got %d on a read, want 200", resp.StatusCode)
	}

	denied := []struct{ method, path string }{
		{http.MethodPost, "/v0/sandboxes"},
		{http.MethodDelete, "/v0/sandboxes/s1"},
		{http.MethodPost, "/v0/sandboxes/s1/exec"},
		{http.MethodGet, "/v0/secrets"},
	}
	for _, d := range denied {
		resp := askRoute(t, address, token, d.method, d.path) //nolint:bodyclose // askRoute closes the body in a cleanup
		if resp.StatusCode != http.StatusForbidden {
			t.Errorf("a sandbox:read token got %d on %s %s, want 403", resp.StatusCode, d.method, d.path)
		}

		var body struct {
			Error struct {
				Code    models.Code `json:"code"`
				Message string      `json:"message"`
			} `json:"error"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
			t.Fatalf("%s %s: decode the refusal: %v", d.method, d.path, err)
		}
		if body.Error.Code != models.CodeForbidden || body.Error.Message == "" {
			t.Errorf("%s %s: the refusal reads %+v, want a line and the code forbidden", d.method, d.path, body)
		}
	}

	// The one read dialed the socket; every forbidden route was answered without a dial.
	if dialed := up.dialed.Load(); dialed != 1 {
		t.Errorf("the front dialed the socket %d times, want 1 for the single read it allowed", dialed)
	}
}

// A token with no scopes and a token with a "*" scope both reach a write route.
func TestAFullTokenReachesAWriteRoute(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)

	for name, token := range map[string]string{
		"no scopes": mint(t, env, "root"),
		"star":      mintScoped(t, env, "root", "*"),
	} {
		if resp := askRoute(t, address, token, http.MethodPost, "/v0/sandboxes"); resp.StatusCode != http.StatusOK { //nolint:bodyclose // askRoute closes the body in a cleanup
			t.Errorf("%s: a full token got %d on a write, want 200", name, resp.StatusCode)
		}
	}
}

// An unknown route is 403 for any token, and the front never dials the daemon for it.
func TestAnUnknownRouteIs403AndNothingIsDialed(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)

	resp := askRoute(t, address, mint(t, env, "root"), http.MethodGet, "/v0/nonesuch") //nolint:bodyclose // askRoute closes the body in a cleanup
	if resp.StatusCode != http.StatusForbidden {
		t.Errorf("an unknown route got %d, want 403", resp.StatusCode)
	}
	if dialed := up.dialed.Load(); dialed != 0 {
		t.Errorf("the front dialed the socket %d times for an unknown route, want none", dialed)
	}
}

// Every route the daemon serves has a capability, so no request reaches the front without one to check.
func TestEveryDaemonRouteHasACapability(t *testing.T) {
	covered := 0
	for _, r := range api.Routes() {
		covered++
		if _, ok := capabilityOf(r); !ok {
			t.Errorf("route %s %s has no capability", r.Method, r.Pattern)
		}
	}

	// An empty route list would pass in silence, so the walk proves it covered the daemon surface.
	if covered < 15 {
		t.Fatalf("the walk covered %d daemon routes, want the full set", covered)
	}
}

// A non-101 answer to a handshake ends after one response, so a pipelined second request never reaches the daemon.
func TestANonUpgradeAnswerDoesNotForwardAPipelinedRequest(t *testing.T) {
	up := plainDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)
	token := mint(t, env, "root")

	conn, err := tls.Dial("tcp", address, &tls.Config{InsecureSkipVerify: true}) //nolint:gosec // G402: the certificate is generated by this test
	if err != nil {
		t.Fatalf("dial the front: %v", err)
	}
	defer conn.Close()

	handshake := "GET /v0/sandboxes/s1/logs HTTP/1.1\r\nHost: box\r\nAuthorization: Bearer " + token +
		"\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n"
	pipelined := "GET /v0/sandboxes HTTP/1.1\r\nHost: box\r\nAuthorization: Bearer " + token + "\r\n\r\n"
	if _, err := io.WriteString(conn, handshake+pipelined); err != nil {
		t.Fatalf("write the pipelined requests: %v", err)
	}

	// The front relays the daemon's one non-101 response and closes; ReadAll ends when it does.
	if _, err := io.ReadAll(conn); err != nil {
		t.Fatalf("read the front's answer: %v", err)
	}

	if got := drain(up.requests); len(got) != 1 {
		t.Errorf("the daemon saw %d requests, want only the handshake, never the pipelined one: %v", len(got), got)
	}
}

func TestReadSecretRefusesAFileTheHostCanRead(t *testing.T) {
	path := secretFile(t, testSecret)
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	_, err := ReadSecret(path)
	if err == nil {
		t.Fatal("a world-readable secret file was accepted")
	}
	if strings.Contains(err.Error(), testSecret) {
		t.Error("the refusal carries the secret value")
	}
}

func TestReadSecretRefusesAnEmptyFileAndNoFile(t *testing.T) {
	if _, err := ReadSecret(secretFile(t, "  \n")); err == nil {
		t.Error("an empty secret file was accepted")
	}
	if _, err := ReadSecret(""); err == nil {
		t.Error("no secret file at all was accepted")
	}
}

func TestReadSecretRefusesASecretUnder32Bytes(t *testing.T) {
	_, err := ReadSecret(secretFile(t, strings.Repeat("a", 31)))
	if err == nil {
		t.Fatal("a 31-byte secret was accepted")
	}
	if !strings.Contains(err.Error(), "31 bytes") || !strings.Contains(err.Error(), "openssl rand -hex 32") {
		t.Errorf("the refusal is %q, want the byte count and the generation line", err.Error())
	}

	if _, err := ReadSecret(secretFile(t, strings.Repeat("a", 32))); err != nil {
		t.Errorf("a 32-byte secret was refused: %v", err)
	}
	// openssl rand -hex 32 prints 64 hex characters, the documented way to make one.
	if _, err := ReadSecret(secretFile(t, strings.Repeat("0123456789abcdef", 4))); err != nil {
		t.Errorf("the openssl rand -hex 32 line was refused: %v", err)
	}
}

func TestReadTokenRefusesAFileTheHostCanRead(t *testing.T) {
	path := tokenFile(t, "cli-token")
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	if _, err := ReadToken(path); err == nil {
		t.Fatal("a world-readable token file was accepted")
	}
}

func TestReadTokenTrimsTheFile(t *testing.T) {
	token, err := ReadToken(tokenFile(t, "cli-token\n"))
	if err != nil {
		t.Fatalf("ReadToken: %v", err)
	}
	if token != "cli-token" {
		t.Errorf("ReadToken answered %q, want the trimmed token", token)
	}
}

// A token minted with no duration carries no exp, still verifies, and lists as active.
func TestMintWithNoDurationHasNoExpiry(t *testing.T) {
	env := newTokenEnv(t)

	minted, err := IssueToken([]byte(testSecret), env.tokens, "ci", nil, 0)
	if err != nil {
		t.Fatalf("IssueToken: %v", err)
	}
	if minted.ExpiresAt != nil {
		t.Errorf("the record carries expires_at %s, want none for a token that never expires", minted.ExpiresAt)
	}

	if _, _, _, err := verify([]byte(testSecret), minted.Token); err != nil {
		t.Fatalf("verify a token with no expiry: %v", err)
	}

	infos, err := ListTokens(env.tokens)
	if err != nil {
		t.Fatalf("ListTokens: %v", err)
	}
	if len(infos) != 1 || infos[0].Status != StatusActive || infos[0].ExpiresAt != nil {
		t.Errorf("the ledger lists %+v, want one active token with no expiry", infos)
	}
}

// A token whose signature is valid but whose id the ledger does not hold is 401, and nothing is dialed.
func TestATokenNotInTheLedgerIs401(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)

	// Mint signs without recording, so the token is well-formed but absent from the front's ledger.
	token, err := Mint([]byte(testSecret), "ghost", nil, time.Hour)
	if err != nil {
		t.Fatalf("Mint: %v", err)
	}

	resp := ask(t, address, token) //nolint:bodyclose // ask closes the body in a cleanup
	if resp.StatusCode != http.StatusUnauthorized {
		t.Errorf("a token not in the ledger got %d, want 401", resp.StatusCode)
	}
	if dialed := up.dialed.Load(); dialed != 0 {
		t.Errorf("the front dialed the socket %d times for a token not in the ledger, want none", dialed)
	}
}

// A token works, then a revoke marks it in the ledger, and the very next request with it is 401, no restart.
func TestARevokedTokenIs401OnTheNextRequest(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)
	token := mint(t, env, "ci")

	if resp := ask(t, address, token); resp.StatusCode != http.StatusOK { //nolint:bodyclose // ask closes the body in a cleanup
		t.Fatalf("the token got %d before the revoke, want 200", resp.StatusCode)
	}

	found, err := RevokeSubject(env.tokens, "ci")
	if err != nil {
		t.Fatalf("RevokeSubject: %v", err)
	}
	if found != 1 {
		t.Fatalf("revoke matched %d tokens, want 1", found)
	}

	if resp := ask(t, address, token); resp.StatusCode != http.StatusUnauthorized { //nolint:bodyclose // ask closes the body in a cleanup
		t.Errorf("the token got %d after the revoke, want 401", resp.StatusCode)
	}
}

// A ledger that was there and then vanishes refuses every request; the front never downgrades to no ledger.
func TestAVanishedLedgerRefusesEveryRequest(t *testing.T) {
	up := fakeDaemon(t)
	env := newTokenEnv(t)
	address := front(t, up.root, env.secret)
	token := mint(t, env, "ci")

	if resp := ask(t, address, token); resp.StatusCode != http.StatusOK { //nolint:bodyclose // ask closes the body in a cleanup
		t.Fatalf("the token got %d before the ledger vanished, want 200", resp.StatusCode)
	}

	if err := os.Remove(env.tokens); err != nil {
		t.Fatalf("remove the ledger: %v", err)
	}

	if resp := ask(t, address, token); resp.StatusCode != http.StatusUnauthorized { //nolint:bodyclose // ask closes the body in a cleanup
		t.Errorf("the token got %d after the ledger vanished, want 401", resp.StatusCode)
	}
}

// The front refuses to start when a ledger others can read is there, because it names every valid token.
func TestTheFrontRefusesAWorldReadableLedger(t *testing.T) {
	env := newTokenEnv(t)
	if _, err := IssueToken([]byte(testSecret), env.tokens, "ci", nil, time.Hour); err != nil {
		t.Fatalf("IssueToken: %v", err)
	}
	if err := os.Chmod(env.tokens, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	cert, key := keyPair(t)
	_, err := New(Config{Listen: "127.0.0.1:0", CertFile: cert, KeyFile: key, SecretFile: env.secret, Root: shortRoot(t), Out: io.Discard})
	if err == nil {
		t.Error("the front started with a world-readable ledger, want a refusal")
	}
}

// ListTokens reads active, revoked and expired straight from the ledger records.
func TestListTokensReadsEachStatus(t *testing.T) {
	path := filepath.Join(t.TempDir(), TokensFileName)

	now := time.Now().UTC().Truncate(time.Second)
	past := now.Add(-time.Hour)
	entries := []ledgerEntry{
		{JTI: "active-id", Sub: "a", IssuedAt: now, Scopes: []string{"*"}},
		{JTI: "revoked-id", Sub: "b", IssuedAt: now, Scopes: []string{"*"}, Revoked: true},
		{JTI: "expired-id", Sub: "c", IssuedAt: past, ExpiresAt: &past, Scopes: []string{"*"}},
	}
	for _, e := range entries {
		if err := appendEntry(path, e); err != nil {
			t.Fatalf("appendEntry: %v", err)
		}
	}

	infos, err := ListTokens(path)
	if err != nil {
		t.Fatalf("ListTokens: %v", err)
	}

	want := map[string]TokenStatus{"active-id": StatusActive, "revoked-id": StatusRevoked, "expired-id": StatusExpired}
	if len(infos) != len(want) {
		t.Fatalf("ListTokens read %d tokens, want %d", len(infos), len(want))
	}
	for _, info := range infos {
		if info.Status != want[info.ID] {
			t.Errorf("token %s lists as %s, want %s", info.ID, info.Status, want[info.ID])
		}
	}
}

// Revoke by id flips one token; revoke by subject flips every token that subject holds; an unknown id matches none.
func TestRevokeMarksTokensInTheLedger(t *testing.T) {
	path := filepath.Join(t.TempDir(), TokensFileName)

	for _, sub := range []string{"alice", "alice", "bob"} {
		if _, err := IssueToken([]byte(testSecret), path, sub, nil, time.Hour); err != nil {
			t.Fatalf("IssueToken: %v", err)
		}
	}

	infos, err := ListTokens(path)
	if err != nil {
		t.Fatalf("ListTokens: %v", err)
	}
	var bob string
	for _, info := range infos {
		if info.Subject == "bob" {
			bob = info.ID
		}
	}

	if found, err := RevokeToken(path, bob); err != nil || found != 1 {
		t.Fatalf("RevokeToken matched %d (err %v), want 1", found, err)
	}
	if found, err := RevokeSubject(path, "alice"); err != nil || found != 2 {
		t.Fatalf("RevokeSubject matched %d (err %v), want 2", found, err)
	}

	infos, err = ListTokens(path)
	if err != nil {
		t.Fatalf("ListTokens: %v", err)
	}
	for _, info := range infos {
		if info.Status != StatusRevoked {
			t.Errorf("token %s of %s lists as %s, want revoked", info.ID, info.Subject, info.Status)
		}
	}

	if found, err := RevokeToken(path, "no-such-id"); err != nil || found != 0 {
		t.Errorf("RevokeToken on an unknown id matched %d (err %v), want 0 and no error", found, err)
	}
}

// IssueToken creates the ledger at 0640 when it is absent, so the group reads it and others do not.
func TestIssueTokenCreatesTheLedger0640(t *testing.T) {
	path := filepath.Join(t.TempDir(), TokensFileName)

	if _, err := IssueToken([]byte(testSecret), path, "ci", nil, time.Hour); err != nil {
		t.Fatalf("IssueToken: %v", err)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat the ledger: %v", err)
	}
	if info.Mode().Perm() != 0o640 {
		t.Errorf("the ledger is at mode %04o, want 0640", info.Mode().Perm())
	}
}

// IssueToken refuses to append to a ledger others can read, so a minted token never lands in an exposed file.
func TestIssueTokenRefusesAWorldReadableLedger(t *testing.T) {
	path := filepath.Join(t.TempDir(), TokensFileName)

	if _, err := IssueToken([]byte(testSecret), path, "ci", nil, time.Hour); err != nil {
		t.Fatalf("IssueToken: %v", err)
	}
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	if _, err := IssueToken([]byte(testSecret), path, "ci", nil, time.Hour); err == nil {
		t.Error("IssueToken appended to a world-readable ledger, want a refusal")
	}
}

// tokenEnv is a secret file and the ledger beside it, so a token minted here lands where the front reads it.
type tokenEnv struct {
	secret string
	tokens string
}

func newTokenEnv(t *testing.T) tokenEnv {
	t.Helper()

	secret := secretFile(t, testSecret)

	return tokenEnv{secret: secret, tokens: TokensPath(secret, "")}
}

// mint issues a valid token for sub over the test secret, records it in env's ledger, and answers it.
func mint(t *testing.T, env tokenEnv, sub string) string {
	t.Helper()

	return mintScoped(t, env, sub)
}

// mintScoped issues a valid token for sub over the test secret, recording it in env's ledger with the scopes named.
func mintScoped(t *testing.T, env tokenEnv, sub string, scopes ...string) string {
	t.Helper()

	minted, err := IssueToken([]byte(testSecret), env.tokens, sub, scopes, time.Hour)
	if err != nil {
		t.Fatalf("mint a token: %v", err)
	}

	return minted.Token
}

// signed builds a token of method over key, for the refusal cases the front must reject.
func signed(t *testing.T, method jwt.SigningMethod, key any, claims jwt.Claims) string {
	t.Helper()

	token, err := jwt.NewWithClaims(method, claims).SignedString(key)
	if err != nil {
		t.Fatalf("sign a test token: %v", err)
	}

	return token
}

func secretFile(t *testing.T, value string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "secret")
	if err := os.WriteFile(path, []byte(value), 0o600); err != nil {
		t.Fatalf("write the secret file: %v", err)
	}

	return path
}

func tokenFile(t *testing.T, value string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "token")
	if err := os.WriteFile(path, []byte(value), 0o600); err != nil {
		t.Fatalf("write the token file: %v", err)
	}

	return path
}

// shortRoot keeps a unix socket path under the 104 bytes macOS allows.
func shortRoot(t *testing.T) string {
	t.Helper()

	root, err := os.MkdirTemp("", "shard") //nolint:usetesting // t.TempDir is too long for a socket path
	if err != nil {
		t.Fatalf("make a root: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(root) })

	return root
}

// keyPair writes a self-signed certificate for 127.0.0.1 and answers the two paths.
func keyPair(t *testing.T) (string, string) {
	t.Helper()

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generate a key: %v", err)
	}

	template := x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "localhost"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IsCA:         true,
	}

	der, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		t.Fatalf("sign the certificate: %v", err)
	}

	marshalled, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		t.Fatalf("marshal the key: %v", err)
	}

	dir := t.TempDir()
	certPath, keyPath := filepath.Join(dir, "cert.pem"), filepath.Join(dir, "key.pem")

	if err := os.WriteFile(certPath, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o600); err != nil {
		t.Fatalf("write the certificate: %v", err)
	}
	if err := os.WriteFile(keyPath, pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: marshalled}), 0o600); err != nil {
		t.Fatalf("write the key: %v", err)
	}

	return certPath, keyPath
}
