# Generated by scripts/unasync.py from src/useshards/_async/_files.py. Edit that file, not this one.
"""A sandbox's files: one file over /files, a directory as a tar over /archive, and every transfer streamed."""

from __future__ import annotations

import builtins
import errno
import functools
import json
import os
import posixpath
import stat
import tempfile
from collections.abc import Iterable, Iterator, Mapping
from typing import IO

import httpx

from .. import _archive
from .._generated import models
from .._generated.api.files import delete_file, list_dir, make_dir, read_file, stat_file
from .._generated.types import UNSET, File
from .._types import FileEntry, FileInfo, file_entry, file_info
from .._wire import path as route
from ..errors import APIError, ProtocolError, UnknownLengthError
from . import _backend
from ._transport import CHUNK, Transport, body

STAT_HEADER = "X-Shard-Stat"

LocalPath = str | os.PathLike[str]


class Files:
    """The files of one sandbox. A sandbox path is absolute; a local path is on this host."""

    def __init__(self, transport: Transport, sandbox: str) -> None:
        self._transport = transport
        self._sandbox = sandbox

    def read(self, path: str) -> bytes:
        """copy a file out of a running sandbox"""
        file = self._transport.answer(
            File, lambda: read_file.sync_detailed(self._sandbox, client=self._transport.api, path=path)
        )
        return file.payload.read()

    def read_text(self, path: str, encoding: str = "utf-8") -> str:
        """copy a file out of a running sandbox"""
        return (self.read(path)).decode(encoding)

    def write(
        self,
        path: str,
        data: str | bytes | IO[bytes],
        *,
        size: int | None = None,
        mode: int | None = None,
        parents: bool = False,
        user: str | None = None,
    ) -> None:
        """copy a file into a running sandbox"""
        if isinstance(data, str):
            data = data.encode()
        if isinstance(data, bytes):
            if size is not None and size != len(data):
                raise ValueError(f"write {path}: size={size}, but the data holds {len(data)} bytes")
            self._put(path, data, len(data), mode=mode, parents=parents, user=user)
            return
        if size is not None:
            content = _exactly(data, size, f"write {path}", to_end=False)
            self._put(path, content, size, mode=mode, parents=parents, user=user)
            return
        if not data.seekable():
            raise UnknownLengthError(f"write {path}: the data is a stream of unknown length, so pass size=")
        here = data.tell()
        size = data.seek(0, os.SEEK_END) - here
        data.seek(here)
        content = _exactly(data, size, f"write {path}", to_end=True)
        self._put(path, content, size, mode=mode, parents=parents, user=user)

    def stat(self, path: str) -> FileInfo:
        try:
            response = self._transport.send(
                lambda: stat_file.sync_detailed(self._sandbox, client=self._transport.api, path=path)
            )
        except APIError as e:
            # A HEAD refusal carries no body, so the SDK names the path the daemon could not.
            raise type(e)(e.status, e.code, f"the daemon answered {e.status} to a stat of {path}") from None
        return _stat_of(response.headers, f"stat {path}")

    def list(self, path: str) -> builtins.list[FileEntry]:
        """The entries of the directory at path, each with its own stat."""
        try:
            listing = self._transport.answer(
                models.EntriesResponse,
                lambda: list_dir.sync_detailed(self._sandbox, client=self._transport.api, path=path),
            )
        except ProtocolError:
            # The daemon closes the JSON only once the guest sent every entry, so a cut listing never parses.
            raise ProtocolError(f"the daemon cut the listing of {path} short") from None
        return [file_entry(entry) for entry in listing.entries]

    def mkdir(self, path: str, *, mode: int | None = None, parents: bool = False, user: str | None = None) -> None:
        body = models.MkdirRequest(
            path=path,
            mode=UNSET if mode is None else format(mode, "o"),
            parents=parents or UNSET,
            user=user or UNSET,
        )
        self._transport.send(lambda: make_dir.sync_detailed(self._sandbox, client=self._transport.api, body=body))

    def remove(self, path: str, *, recursive: bool = False) -> None:
        self._transport.send(
            lambda: delete_file.sync_detailed(
                self._sandbox, client=self._transport.api, path=path, recursive=recursive or UNSET
            )
        )

    def upload(
        self,
        local: LocalPath,
        remote: str,
        *,
        mode: int | None = None,
        parents: bool = False,
        user: str | None = None,
    ) -> None:
        """copy a file into a running sandbox"""
        source = os.fspath(local)
        with _backend.offload(functools.partial(_reader, source)) as f:
            info = os.fstat(f.fileno())
            if not stat.S_ISREG(info.st_mode):
                raise UnknownLengthError(f"upload {source}: not a regular file, so its length is not known up front")
            content = _exactly(f, info.st_size, f"upload {source}", to_end=True)
            mode = stat.S_IMODE(info.st_mode) & 0o777 if mode is None else mode
            self._put(remote, content, info.st_size, mode=mode, parents=parents, user=user)

    def download(self, remote: str, local: LocalPath) -> None:
        """copy a file out of a running sandbox"""
        target = os.fspath(local)
        fd, tmp = tempfile.mkstemp(prefix=f".{os.path.basename(target)}.useshards-", dir=os.path.dirname(target) or ".")
        try:
            with os.fdopen(fd, "wb") as out:
                with self._transport.stream(self._route("files"), {"path": remote}) as response:
                    info = _stat_of(response.headers, f"download {remote}")
                    _spool(response, out)
                _backend.offload(functools.partial(os.fsync, out.fileno()))
            os.chmod(tmp, info.mode & 0o777)
            os.replace(tmp, target)
        except BaseException:
            _discard(tmp)
            raise

    def upload_dir(self, local: LocalPath, remote: str, *, user: str | None = None) -> None:
        """copy a directory into a running sandbox"""
        source = os.fspath(local)
        parent, name = _split(remote)
        if not os.path.isdir(source):
            raise NotADirectoryError(errno.ENOTDIR, os.strerror(errno.ENOTDIR), source)
        params = {"path": parent}
        if user:
            params["user"] = user
        # The tar goes to disk first, since the daemon takes a known length and the pack only knows it at the end.
        with tempfile.TemporaryFile() as tar:
            _backend.offload(functools.partial(_archive.pack, source, name, tar))
            size = tar.tell()
            tar.seek(0)
            content = _exactly(tar, size, f"upload {source}", to_end=True)
            self._transport.put(self._route("archive"), params, content, size)

    def download_dir(self, remote: str, local: LocalPath) -> None:
        """copy a directory out of a running sandbox"""
        _, name = _split(remote)
        target = os.path.abspath(local)
        # The whole tar is in before the unpack starts, so a cut never lands half a tree.
        with tempfile.TemporaryFile() as tar:
            with self._transport.stream(self._route("archive"), {"path": posixpath.normpath(remote)}) as response:
                info = _stat_of(response.headers, f"download {remote}")
                if info.type != "dir":
                    raise NotADirectoryError(f"download {remote}: it is a {info.type}, not a directory")
                _spool(response, tar)
            tar.seek(0)
            try:
                os.mkdir(target, 0o700)
                made = True
            except FileExistsError:
                made = False
            if not stat.S_ISDIR(os.lstat(target).st_mode):
                raise NotADirectoryError(errno.ENOTDIR, os.strerror(errno.ENOTDIR), target)
            _backend.offload(functools.partial(_archive.unpack, tar, target, name))
        # A directory already there keeps its mode, so only one this call made takes the sandbox's.
        if made:
            os.chmod(target, info.mode & 0o777)

    def _put(
        self,
        path: str,
        content: bytes | Iterable[bytes],
        size: int,
        *,
        mode: int | None,
        parents: bool,
        user: str | None,
    ) -> None:
        params = {"path": path}
        if mode is not None:
            params["mode"] = format(mode, "o")
        if parents:
            params["parents"] = "true"
        if user:
            params["user"] = user
        self._transport.put(self._route("files"), params, content, size)

    def _route(self, verb: str) -> str:
        return route("sandboxes", self._sandbox, verb)


def _exactly(source: IO[bytes], size: int, what: str, *, to_end: bool) -> Iterator[bytes]:
    """Send exactly size bytes, so the daemon never lands a file the source cut short, or with to_end one that grew."""
    left = size
    while left > 0:
        # The last read asks one byte more, so a source that grew fails before the daemon has every byte.
        want = left + 1 if to_end and left <= CHUNK else min(CHUNK, left)
        chunk = _backend.offload(functools.partial(source.read, want))
        if len(chunk) > left:
            raise UnknownLengthError(f"{what}: the data grew past the {size} bytes it held at the start")
        if not chunk:
            raise UnknownLengthError(f"{what}: the data ended {left} bytes short of the {size} it held at the start")
        left -= len(chunk)
        yield chunk
    if not to_end:
        return
    extra = _backend.offload(functools.partial(source.read, 1))
    if extra:
        raise UnknownLengthError(f"{what}: the data grew past the {size} bytes it held at the start")


def _spool(response: httpx.Response, out: IO[bytes]) -> None:
    for chunk in body(response):
        _backend.offload(functools.partial(out.write, chunk))


def _stat_of(headers: Mapping[str, str], what: str) -> FileInfo:
    raw = headers.get(STAT_HEADER)
    if raw is None:
        raise ProtocolError(f"{what}: the daemon answered no {STAT_HEADER} header")
    try:
        record = json.loads(raw)
    except ValueError:
        raise ProtocolError(f"{what}: the daemon answered a {STAT_HEADER} header that is not JSON") from None
    return file_info(record)


def _split(remote: str) -> tuple[str, str]:
    """The sandbox directory a tar lands in or comes from, and the name of its top entry."""
    clean = posixpath.normpath(remote)
    name = posixpath.basename(clean)
    if not posixpath.isabs(clean) or name in ("", ".", ".."):
        raise ValueError(f"{remote!r} must be an absolute sandbox path below /")
    return posixpath.dirname(clean), name


def _reader(local: str) -> IO[bytes]:
    return open(local, "rb")


def _discard(tmp: str) -> None:
    try:
        os.remove(tmp)
    except FileNotFoundError:
        return
