# Generated by scripts/unasync.py from src/useshards/_async/_follow.py. Edit that file, not this one.
"""A log as it arrives: one WebSocket, opened on the first read and let go of by the end, a fault or a close."""

from __future__ import annotations

import json
from collections.abc import Callable
from typing import Generic, Self, TypeVar

from .._frames import CLOSE_NORMAL, OP_BINARY, OP_TEXT, Message
from .._generated import models
from .._types import NetworkLogRecord, network_log_record
from .._wire import EXIT, FAILURE, STDOUT, failure_of
from ..errors import ProtocolError, ShardConnectionError, failure_error
from . import _backend
from ._transport import Transport
from ._ws import WebSocket

T = TypeVar("T")

# What one message carries, or None for the daemon's end of the log.
Parse = Callable[[Message, str], T | None]


class Follow(Generic[T]):
    """Iterate it, or use it as a context manager that closes it. A close from anywhere ends a read in flight."""

    def __init__(self, transport: Transport, path: str, what: str, parse: Parse[T]) -> None:
        self._transport = transport
        self._path = path
        self._what = what
        self._parse = parse
        self._lock = _backend.Lock()
        self._ws: WebSocket | None = None
        self._reading = False
        self._closed = False
        self._over = False

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def __iter__(self) -> Self:
        return self

    def __next__(self) -> T:
        with self._lock:
            if self._closed or self._over:
                raise StopIteration
            self._reading = True
        try:
            item = self._next()
        except BaseException as e:
            if self._end(e):
                raise StopIteration from None
            raise
        if item is None:
            self._end(None)
            raise StopIteration
        with self._lock:
            self._reading = False
        return item

    def close(self) -> None:
        with self._lock:
            self._closed = True
            reading = self._reading
            ws, self._ws = self._ws, None
        if ws is None:
            return
        # A read blocked on the socket wakes only when the socket goes, so a polite close would wait on it.
        if reading:
            ws.release()
            return
        ws.close()

    def _next(self) -> T | None:
        ws = self._ws or self._open()
        message = ws.receive()
        if message is not None:
            return self._parse(message, self._what)
        if ws.close_code is None:
            raise ShardConnectionError(f"{self._what}: the stream to the daemon dropped")
        if ws.close_code != CLOSE_NORMAL:
            raise failure_error("internal", f"{self._what}: {ws.close_reason or f'closed with {ws.close_code}'}")
        return None

    def _open(self) -> WebSocket:
        ws = WebSocket.connect(self._transport.http, self._path, self._what, {"follow": "true"})
        with self._lock:
            if not self._closed:
                self._ws = ws
                return ws
        ws.release()
        raise StopIteration

    def _end(self, fault: BaseException | None) -> bool:
        """Let go of the stream once the read is over, and answer whether a close came first."""
        with self._lock:
            self._reading = False
            self._over = True
            closed = self._closed
            ws, self._ws = self._ws, None
        if ws is None:
            return closed
        if fault is None:
            ws.close()
            return closed
        try:
            ws.release()
        except Exception as release_error:
            fault.add_note(f"letting go of the stream also failed: {release_error}")
        return closed


def log_chunk(message: Message, what: str) -> bytes | None:
    payload = message.payload
    if message.opcode == OP_BINARY and payload[:1] == bytes([STDOUT]):
        return payload[1:]
    if message.opcode == OP_BINARY and payload[:1] == bytes([EXIT]):
        return None
    if message.opcode == OP_BINARY and payload[:1] == bytes([FAILURE]):
        raise failure_of(payload[1:], what)
    raise ProtocolError(f"{what}: the daemon sent a message the SDK cannot read: {payload[:64]!r}")


def network_log_entry(message: Message, what: str) -> NetworkLogRecord:
    if message.opcode != OP_TEXT:
        raise ProtocolError(f"{what}: the daemon sent a binary message where a record belongs")
    try:
        record = models.Record.from_dict(json.loads(message.payload))
    except (KeyError, TypeError, ValueError):
        raise ProtocolError(f"{what}: the daemon sent a record the SDK cannot read") from None
    return network_log_record(record)
