# Generated by scripts/unasync.py from src/useshards/_async/_sandbox.py. Edit that file, not this one.
"""One sandbox and what runs in it: its commands, the app a run started, its logs and its files."""

from __future__ import annotations

import builtins
from collections.abc import Mapping, Sequence
from typing import Literal, overload

import httpx

from .._capture import DEFAULT_OUTPUT_LIMIT
from .._generated import models
from .._generated.api.app import attach_app, stop_app
from .._generated.api.exec_ import get_exec, list_execs
from .._generated.api.sandboxes import (
    fork_sandbox,
    get_sandbox,
    get_sandbox_egress_log,
    get_sandbox_logs,
    pause_sandbox,
    remove_sandbox,
    resume_sandbox,
    start_sandbox,
    stop_sandbox,
)
from .._generated.types import UNSET
from .._types import (
    AppExit,
    AppInfo,
    CommandInfo,
    CommandResult,
    NetworkLogRecord,
    OutputCallback,
    SandboxInfo,
    TerminalSize,
    app_exit,
    command_info,
    network_log_record,
    sandbox_info,
)
from .._wire import Call, path
from ..errors import ProtocolError, ShardConnectionError
from ._command import Command, run_command, start_command
from ._files import Files
from ._follow import Follow, log_chunk, network_log_entry
from ._transport import Transport


class Sandbox:
    """One sandbox. info is its record as of the last call that answered one; inspect() reads it again."""

    def __init__(self, transport: Transport, info: SandboxInfo) -> None:
        self._transport = transport
        self.info = info
        self.commands = Commands(transport, info.id)
        self.files = Files(transport, info.id)

    def __repr__(self) -> str:
        return f"{type(self).__name__}(id={self.id!r}, name={self.name!r}, state={self.info.state!r})"

    @property
    def id(self) -> str:
        return self.info.id

    @property
    def name(self) -> str | None:
        return self.info.name

    def inspect(self) -> SandboxInfo:
        record = self._transport.answer(
            models.Inspection, lambda: get_sandbox.sync_detailed(self.id, client=self._transport.api)
        )
        self.info = sandbox_info(record)
        return self.info

    @overload
    def exec(
        self,
        command: str | Sequence[str],
        *,
        background: Literal[False] = False,
        stdin: bytes | str | None = None,
        env: Mapping[str, str] | None = None,
        workdir: str | None = None,
        user: str | None = None,
        tty: bool | TerminalSize = False,
        output_limit_bytes: int = DEFAULT_OUTPUT_LIMIT,
        on_stdout: OutputCallback | None = None,
        on_stderr: OutputCallback | None = None,
    ) -> CommandResult: ...

    @overload
    def exec(
        self,
        command: str | Sequence[str],
        *,
        background: Literal[True],
        stdin: bool = False,
        env: Mapping[str, str] | None = None,
        workdir: str | None = None,
        user: str | None = None,
        tty: bool | TerminalSize = False,
        output_limit_bytes: int = DEFAULT_OUTPUT_LIMIT,
        on_stdout: OutputCallback | None = None,
        on_stderr: OutputCallback | None = None,
    ) -> Command: ...

    def exec(
        self,
        command: str | Sequence[str],
        *,
        background: bool = False,
        stdin: bytes | str | bool | None = None,
        env: Mapping[str, str] | None = None,
        workdir: str | None = None,
        user: str | None = None,
        tty: bool | TerminalSize = False,
        output_limit_bytes: int = DEFAULT_OUTPUT_LIMIT,
        on_stdout: OutputCallback | None = None,
        on_stderr: OutputCallback | None = None,
    ) -> CommandResult | Command:
        """execute a command in a running sandbox"""
        if background:
            if stdin is not None and not isinstance(stdin, bool):
                raise TypeError("a background command takes its input through write_stdin(), so stdin is a bool")
            return start_command(
                self._transport,
                self.id,
                command,
                env=env,
                workdir=workdir,
                user=user,
                stdin=stdin is True,
                tty=tty,
                output_limit_bytes=output_limit_bytes,
                on_stdout=on_stdout,
                on_stderr=on_stderr,
            )
        if isinstance(stdin, bool):
            raise TypeError("only a background command keeps its input open; pass the input itself instead")
        return run_command(
            self._transport,
            self.id,
            command,
            env=env,
            workdir=workdir,
            user=user,
            stdin=stdin,
            tty=tty,
            output_limit_bytes=output_limit_bytes,
            on_stdout=on_stdout,
            on_stderr=on_stderr,
        )

    def stop(self) -> None:
        """stop a sandbox and preserve its files"""
        self._verb(lambda: stop_sandbox.sync_detailed(self.id, client=self._transport.api))

    def start(self) -> None:
        """start a stopped sandbox with its saved files"""
        self._verb(lambda: start_sandbox.sync_detailed(self.id, client=self._transport.api))

    def pause(self) -> None:
        """save a sandbox's state and suspend it"""
        self._verb(lambda: pause_sandbox.sync_detailed(self.id, client=self._transport.api))

    def resume(self) -> None:
        """resume a paused sandbox from its saved state"""
        self._verb(lambda: resume_sandbox.sync_detailed(self.id, client=self._transport.api))

    def fork(self, *, name: str | None = None) -> Sandbox:
        """create a sandbox from a running sandbox's memory and files"""
        body = models.CopyRequest(name=name or UNSET)
        record = self._transport.answer(
            models.Sandbox,
            lambda: fork_sandbox.sync_detailed(self.id, client=self._transport.api, body=body),
            self._transport.read_bound(None),
        )
        return Sandbox(self._transport, sandbox_info(record))

    def remove(self, *, force: bool = False) -> None:
        """delete a sandbox and its files"""
        self._transport.send(
            lambda: remove_sandbox.sync_detailed(self.id, client=self._transport.api, force=force or UNSET),
            self._transport.read_bound(None),
        )

    def logs(self) -> str:
        """The app's output so far, both streams as the daemon wrote them."""
        return self._transport.answer(str, lambda: get_sandbox_logs.sync_detailed(self.id, client=self._transport.api))

    def follow_logs(self) -> Follow[bytes]:
        """The app's output from the start of the log, then as it arrives, until the sandbox stops."""
        return Follow(self._transport, path("sandboxes", self.id, "logs"), f"the logs of sandbox {self.id}", log_chunk)

    def network_logs(self) -> builtins.list[NetworkLogRecord]:
        """Every egress decision the daemon still holds, oldest first."""
        records = self._transport.answer(
            builtins.list, lambda: get_sandbox_egress_log.sync_detailed(self.id, client=self._transport.api)
        )
        return [network_log_record(record) for record in records]

    def follow_network_logs(self) -> Follow[NetworkLogRecord]:
        return Follow(
            self._transport,
            path("sandboxes", self.id, "egress-log"),
            f"the network log of sandbox {self.id}",
            network_log_entry,
        )

    def _verb(self, call: Call) -> None:
        self.info = sandbox_info(self._transport.answer(models.Sandbox, call, self._transport.read_bound(None)))


class Commands:
    """The commands started in one sandbox, by this client or any other."""

    def __init__(self, transport: Transport, sandbox: str) -> None:
        self._transport = transport
        self._sandbox = sandbox

    def list(self) -> builtins.list[CommandInfo]:
        records = self._transport.listed(
            models.ExecsResponse,
            lambda cursor: list_execs.sync_detailed(self._sandbox, client=self._transport.api, cursor=cursor),
            lambda page: page.execs,
        )
        return [command_info(record) for record in records]

    def get(
        self,
        id: str,
        *,
        output_limit_bytes: int = DEFAULT_OUTPUT_LIMIT,
        on_stdout: OutputCallback | None = None,
        on_stderr: OutputCallback | None = None,
    ) -> Command:
        """A handle on a command already started; its wait() attaches, so the callbacks see the replay."""
        record = command_info(
            self._transport.answer(
                models.Exec, lambda: get_exec.sync_detailed(self._sandbox, id, client=self._transport.api)
            )
        )
        return Command(
            self._transport,
            record.sandbox,
            record.id,
            stdin=None,
            output_limit_bytes=output_limit_bytes,
            on_stdout=on_stdout,
            on_stderr=on_stderr,
        )


class App:
    """The app a run started. It ends on its own or by stop(); the sandbox outlives it either way."""

    def __init__(self, transport: Transport, sandbox: Sandbox) -> None:
        self._transport = transport
        self.sandbox = sandbox

    def inspect(self) -> AppInfo:
        info = self.sandbox.inspect()
        if info.app is None:
            raise ProtocolError(f"sandbox {info.id} answered a record with no app")
        return info.app

    def wait(self, timeout: float | None = None) -> AppExit:
        """Block until the app ends with no start again left. A timeout ends the wait, never the app."""
        try:
            record = self._transport.answer(
                models.AppExit,
                lambda: attach_app.sync_detailed(self.sandbox.id, client=self._transport.api),
                self._transport.read_bound(timeout),
            )
        except ShardConnectionError as e:
            if isinstance(e.__cause__, httpx.ReadTimeout):
                raise TimeoutError(f"the app of sandbox {self.sandbox.id} did not end within {timeout}s") from None
            raise
        return app_exit(record)

    def logs(self) -> str:
        return self.sandbox.logs()

    def stop(self, *, force: bool = False) -> None:
        """End the app with TERM, or KILL with force, and cancel its restart policy."""
        body = models.AppStopRequest(force=force or UNSET)
        self._transport.send(
            lambda: stop_app.sync_detailed(self.sandbox.id, client=self._transport.api, body=body),
            self._transport.read_bound(None),
        )
