# Generated by scripts/unasync.py from src/useshards/_async/_shard.py. Edit that file, not this one.
"""The client: sandboxes made and found, and the policies, secrets and snapshots they draw on."""

from __future__ import annotations

import builtins
import warnings
from collections.abc import Mapping, Sequence
from types import TracebackType
from typing import Self

from .. import _types
from .._config import PLAIN_WARNING, StrPath, resolve
from .._types import Capabilities, Policy, PolicyRule, Restart, SandboxInfo, SecretInfo, Snapshot, Version
from .._wire import create_body, json_of, path
from ._sandbox import App, Sandbox, listed
from ._transport import DEFAULT_TIMEOUT, Transport

SandboxRef = Sandbox | str


class Shard:
    """A client of one shard daemon. remote and api_key default to SHARD_REMOTE and SHARD_API_KEY."""

    def __init__(
        self,
        remote: str | None = None,
        api_key: str | None = None,
        *,
        ca_file: StrPath | None = None,
        timeout: float | None = DEFAULT_TIMEOUT,
    ) -> None:
        settings = resolve(remote, api_key, ca_file)
        if settings.plain:
            warnings.warn(PLAIN_WARNING, stacklevel=2)
        self._transport = Transport(settings, timeout)
        self.policies = Policies(self._transport)
        self.secrets = Secrets(self._transport)
        self.snapshots = Snapshots(self._transport)

    def __enter__(self) -> Self:
        return self

    def __exit__(
        self, kind: type[BaseException] | None, error: BaseException | None, trace: TracebackType | None
    ) -> None:
        self.close()

    def close(self) -> None:
        self._transport.close()

    def create(
        self,
        image: str | None = None,
        *,
        snapshot: str | None = None,
        name: str | None = None,
        env: Mapping[str, str] | None = None,
        workdir: str | None = None,
        user: str | None = None,
        secrets: Sequence[str] | None = None,
        policy: str | None = None,
        memory_mib: int | None = None,
        vcpus: int | None = None,
        disk_mib: int | None = None,
    ) -> Sandbox:
        """A running sandbox with no app, from an image or a snapshot; exec() runs in it."""
        body = create_body(
            image,
            None,
            snapshot=snapshot,
            name=name,
            env=env,
            workdir=workdir,
            user=user,
            secrets=secrets,
            policy=policy,
            memory_mib=memory_mib,
            vcpus=vcpus,
            disk_mib=disk_mib,
            restart=None,
        )
        return Sandbox(self._transport, self._create(body))

    def run(
        self,
        image: str,
        command: str | Sequence[str],
        *,
        name: str | None = None,
        env: Mapping[str, str] | None = None,
        workdir: str | None = None,
        user: str | None = None,
        secrets: Sequence[str] | None = None,
        policy: str | None = None,
        memory_mib: int | None = None,
        vcpus: int | None = None,
        disk_mib: int | None = None,
        restart: Restart | None = None,
    ) -> App:
        """A sandbox whose app is command. The sandbox outlives the app; remove() it when done."""
        body = create_body(
            image,
            command,
            snapshot=None,
            name=name,
            env=env,
            workdir=workdir,
            user=user,
            secrets=secrets,
            policy=policy,
            memory_mib=memory_mib,
            vcpus=vcpus,
            disk_mib=disk_mib,
            restart=restart,
        )
        return App(self._transport, Sandbox(self._transport, self._create(body)))

    def get(self, ref: str) -> Sandbox:
        """A sandbox by id, id prefix or name."""
        response = self._transport.call("GET", path("sandboxes", ref))
        return Sandbox(self._transport, _types.sandbox_info(json_of(response)))

    def list(self, *, all: bool = False) -> builtins.list[Sandbox]:
        """The running sandboxes, or with all every sandbox the daemon holds a record of."""
        records = listed(self._transport, path("sandboxes"), "sandboxes", {"all": "true"} if all else None)
        return [Sandbox(self._transport, _types.sandbox_info(record)) for record in records]

    def version(self) -> Version:
        return _types.version(json_of(self._transport.call("GET", path("version"))))

    def capabilities(self) -> Capabilities:
        return _types.capabilities(json_of(self._transport.call("GET", path("capabilities"))))

    def _create(self, body: dict[str, object]) -> SandboxInfo:
        response = self._transport.call(
            "POST", path("sandboxes"), json=body, params={"wait": "true"}, timeout=self._transport.read_bound(None)
        )
        return _types.sandbox_info(json_of(response))


class Policies:
    """Named egress policies, and which sandbox enforces which."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def set(self, name: str, rules: Sequence[PolicyRule]) -> Policy:
        """Make the policy, or replace every rule of it; a sandbox it is assigned to enforces the new rules."""
        body = {"rules": [{"action": rule.action, "rule": rule.rule} for rule in rules]}
        return _types.policy(json_of(self._transport.call("PUT", path("policies", name), json=body)))

    def get(self, name: str) -> Policy:
        return _types.policy(json_of(self._transport.call("GET", path("policies", name))))

    def list(self) -> builtins.list[Policy]:
        """Every policy with its rules; holders and dns come only from get()."""
        return [_types.policy(record) for record in listed(self._transport, path("policies"), "policies")]

    def remove(self, name: str) -> None:
        self._transport.call("DELETE", path("policies", name))

    def assign(self, sandbox: SandboxRef, name: str) -> SandboxInfo:
        return _changed(self._transport, sandbox, "PUT", path("sandboxes", _id(sandbox), "policy"), {"policy": name})

    def clear(self, sandbox: SandboxRef) -> SandboxInfo:
        return _changed(self._transport, sandbox, "DELETE", path("sandboxes", _id(sandbox), "policy"))


class Secrets:
    """Secrets by name. The SDK sends a value and never reads one back."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def set(
        self,
        name: str,
        *,
        value: str,
        destinations: Sequence[str] | None = None,
        placeholder: str | None = None,
    ) -> SecretInfo:
        """Make the secret or replace it. A sandbox sees only the placeholder; the proxy swaps in the value."""
        body: dict[str, object] = {"value": value}
        if destinations is not None:
            body["destinations"] = builtins.list(destinations)
        if placeholder is not None:
            body["placeholder"] = placeholder
        return _types.secret_info(json_of(self._transport.call("PUT", path("secrets", name), json=body)))

    def list(self) -> builtins.list[SecretInfo]:
        return [_types.secret_info(record) for record in listed(self._transport, path("secrets"), "secrets")]

    def remove(self, name: str, *, force: bool = False) -> None:
        """Remove a secret no sandbox is granted; force revokes it from each first."""
        self._transport.call("DELETE", path("secrets", name), params={"force": "true"} if force else None)

    def grant(self, sandbox: SandboxRef, name: str) -> SandboxInfo:
        return _changed(self._transport, sandbox, "POST", path("sandboxes", _id(sandbox), "secrets", name))

    def revoke(self, sandbox: SandboxRef, name: str) -> SandboxInfo:
        return _changed(self._transport, sandbox, "DELETE", path("sandboxes", _id(sandbox), "secrets", name))


class Snapshots:
    """Snapshots of stopped sandboxes, which create(snapshot=) makes new sandboxes from."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, sandbox: SandboxRef, *, name: str | None = None) -> Snapshot:
        body = {"sandbox": _id(sandbox)}
        if name:
            body["name"] = name
        response = self._transport.call("POST", path("snapshots"), json=body, timeout=self._transport.read_bound(None))
        return _types.snapshot(json_of(response))

    def list(self) -> builtins.list[Snapshot]:
        return [_types.snapshot(record) for record in listed(self._transport, path("snapshots"), "snapshots")]

    def inspect(self, ref: str) -> Snapshot:
        """A snapshot by id, id prefix or name."""
        return _types.snapshot(json_of(self._transport.call("GET", path("snapshots", ref))))

    def remove(self, ref: str) -> None:
        self._transport.call("DELETE", path("snapshots", ref))


def _id(sandbox: SandboxRef) -> str:
    return sandbox.id if isinstance(sandbox, Sandbox) else sandbox


def _changed(transport: Transport, sandbox: SandboxRef, method: str, route: str, body: object = None) -> SandboxInfo:
    """Send a change to a sandbox's record, and keep a handle's info current with the answer."""
    info = _types.sandbox_info(json_of(transport.call(method, route, json=body)))
    if isinstance(sandbox, Sandbox):
        sandbox.info = info
    return info
