# Generated by scripts/unasync.py from src/useshards/_async/_transport.py. Edit that file, not this one.
"""The one HTTPX client every call rides, the generated client over it, and every non-2xx answer as an APIError."""

from __future__ import annotations

import contextvars
import functools
from collections.abc import Callable, Iterable, Iterator, Sequence
from contextlib import contextmanager
from typing import Any, Protocol, TypeVar

import httpx

from .._config import Settings
from .._generated.client import Client
from .._generated.types import UNSET, Response, Unset
from .._version import __version__
from .._wire import Call, Fetch, connection_error
from ..errors import ProtocolError, api_error

DEFAULT_TIMEOUT = 60.0
CHUNK = 1 << 20

M = TypeVar("M")
R = TypeVar("R")

# A generated call takes no timeout, so a call that waits on the guest leaves its bound here for the request hook.
_bound: contextvars.ContextVar[httpx.Timeout | None] = contextvars.ContextVar("useshards_timeout", default=None)


class Page(Protocol):
    @property
    def next_(self) -> None | str: ...


P = TypeVar("P", bound=Page)


class Transport:
    def __init__(self, settings: Settings, timeout: float | None, transport: httpx.BaseTransport | None = None) -> None:
        self.timeout = timeout
        self.http = httpx.Client(
            base_url=settings.base_url,
            transport=transport,
            headers={"Authorization": f"Bearer {settings.api_key}", "User-Agent": f"useshards-python/{__version__}"},
            verify=settings.verify,
            timeout=timeout,
            event_hooks={"request": [_bind], "response": [_refuse]},
        )
        self.api = Client(base_url=settings.base_url).set_httpx_client(self.http)

    def read_bound(self, read: float | None) -> httpx.Timeout:
        """The client's timeout with its read bound replaced, for a call that waits on the guest."""
        return httpx.Timeout(self.timeout, read=read)

    def send(self, call: Call, timeout: httpx.Timeout | None = None) -> Response[Any]:
        """Run a generated call; a dropped connection is a ShardConnectionError, an unreadable body a ProtocolError."""
        token = _bound.set(timeout)
        try:
            return call()
        except httpx.TransportError as e:
            raise connection_error(e.request, e) from e
        except (KeyError, TypeError, ValueError) as e:
            raise ProtocolError(f"the daemon answered a body the SDK cannot read: {e!r}") from None
        finally:
            _bound.reset(token)

    def answer(self, kind: type[M], call: Call, timeout: httpx.Timeout | None = None) -> M:
        """The model a generated call parsed from its 2xx answer."""
        parsed = (self.send(call, timeout)).parsed
        if not isinstance(parsed, kind):
            raise ProtocolError(f"the daemon answered {type(parsed).__name__} where {kind.__name__} belongs")
        return parsed

    def listed(self, kind: type[P], fetch: Fetch, rows: Callable[[P], Sequence[R]]) -> list[R]:
        """Every row of a paged list, one page after another."""
        out: list[R] = []
        for page in self.pages(kind, fetch):
            out.extend(rows(page))
        return out

    def pages(self, kind: type[P], fetch: Fetch) -> Iterator[P]:
        cursor: str | Unset = UNSET
        while True:
            page = self.answer(kind, functools.partial(fetch, cursor))
            yield page
            if not page.next_:
                return
            cursor = page.next_

    def put(self, path: str, params: dict[str, str], content: bytes | Iterable[bytes], size: int) -> None:
        """A body of a known length; the generated client takes a file it buffers, never a stream."""
        # An explicit length keeps HTTPX from sending the stream chunked, which the daemon refuses.
        request = self.http.build_request(
            "PUT", path, params=params, content=content, headers={"Content-Length": str(size)}
        )
        try:
            self.http.send(request)
        except httpx.TransportError as e:
            raise connection_error(request, e) from e

    @contextmanager
    def stream(self, path: str, params: dict[str, str]) -> Iterator[httpx.Response]:
        """A GET whose body the caller reads as it arrives; the generated client buffers the whole body."""
        request = self.http.build_request("GET", path, params=params)
        try:
            response = self.http.send(request, stream=True)
        except httpx.TransportError as e:
            raise connection_error(request, e) from e
        try:
            yield response
        finally:
            response.close()

    def close(self) -> None:
        self.http.close()


def body(response: httpx.Response) -> Iterator[bytes]:
    """A streamed body as it arrives, a cut named as the dropped call it is."""
    try:
        for chunk in response.iter_bytes(CHUNK):
            yield chunk
    except httpx.TransportError as e:
        raise connection_error(response.request, e) from e


def _bind(request: httpx.Request) -> None:
    timeout = _bound.get()
    if timeout is not None:
        request.extensions["timeout"] = timeout.as_dict()


def _refuse(response: httpx.Response) -> None:
    """Raise every answer but a 2xx or a WebSocket upgrade, once the daemon's error body is in."""
    if response.is_success or response.status_code == 101:
        return
    response.read()
    raise api_error(response.status_code, response.content)
