# Generated by scripts/unasync.py from suite/_async/apps.py. Edit that file, not this one.
from __future__ import annotations

from useshards import ExitStatus, Restart

from .._shared import equal, ok
from .harness import Check, Context
from .mode import sleep


def run_handle(ctx: Context) -> None:
    command = ["sh", "-c", "echo up; sleep 300"]
    app = ctx.run(command)
    ok(len(app.sandbox.id) > 0, "the handle holds its sandbox")
    equal(app.sandbox.info.state, "running")
    info = app.inspect()
    equal(info.command, tuple(command))
    equal(info.exit_status, None, "a running app has no exit yet")
    equal(info.restart, None, "run with no restart option sets no policy")
    record = (app.sandbox.inspect()).app
    equal(record.command if record is not None else None, tuple(command), "the sandbox record names its app")


def sandbox_exec(ctx: Context) -> None:
    app = ctx.run(["sleep", "300"])
    result = app.sandbox.exec(["ps", "-o", "args"])
    equal(result.exit_code, 0, result.stderr)
    ok("sleep 300" in result.stdout.split("\n"), "a command in the app's sandbox sees the app")


def inspect_logs_wait(ctx: Context) -> None:
    app = ctx.run("echo out; echo err >&2; exit 4")
    exit_ = app.wait()
    equal(exit_.exit_code, 4)
    equal(exit_.signal, None)
    equal(exit_.restarts, 0)
    equal((app.inspect()).exit_status, ExitStatus(code=4, signal=None))
    logs = app.logs()
    ok("out\n" in logs and "err\n" in logs, f"the logs hold both streams: {logs!r}")
    equal((app.sandbox.inspect()).state, "running", "the sandbox outlives its app")
    equal((app.sandbox.exec("echo after")).stdout, "after\n")


def stop_keeps_sandbox(ctx: Context) -> None:
    # always would start a TERMed app again, so the stop must cancel the policy, not only signal the app.
    app = ctx.run(["sleep", "300"], restart=Restart(policy="always", backoff=1))
    app.stop()
    exit_ = app.wait()
    equal(exit_.signal, 15, "stop ends the app with TERM")
    equal(exit_.restarts, 0)
    sleep(3)
    restart = (app.inspect()).restart
    if restart is None:
        raise AssertionError("the app reports its policy")
    equal(restart.count, 0, "no start again follows the stop, past the backoff")
    equal(restart.ended, True)
    equal((app.sandbox.inspect()).state, "running", "stop ends the app and keeps the sandbox")
    ps = app.sandbox.exec(["ps", "-o", "args"])
    ok("sleep 300" not in ps.stdout.split("\n"), f"the app is gone: {ps.stdout!r}")


def restart_policy(ctx: Context) -> None:
    app = ctx.run("echo start; exit 1", restart=Restart(policy="on-failure", retries=2, backoff=1))
    exit_ = app.wait()
    equal(exit_.exit_code, 1)
    equal(exit_.restarts, 2, "wait answers once the retries are spent")
    restart = (app.inspect()).restart
    if restart is None:
        raise AssertionError("the app reports its policy")
    equal(restart.policy, "on-failure")
    equal(restart.retries, 2)
    equal(restart.count, 2)
    equal(restart.gave_up, True)
    equal(restart.ended, True)
    starts = [line for line in (app.logs()).split("\n") if line == "start"]
    equal(len(starts), 3, "the first start and two more")


CHECKS = [
    Check("apps.run_handle", run_handle),
    Check("apps.sandbox_exec", sandbox_exec),
    Check("apps.inspect_logs_wait", inspect_logs_wait),
    Check("apps.stop_keeps_sandbox", stop_keeps_sandbox),
    Check("apps.restart_policy", restart_policy),
]
