# Generated by scripts/unasync.py from suite/_async/auth.py. Edit that file, not this one.
from __future__ import annotations

import json
import os

from useshards import AuthenticationError, ConfigurationError, Sandbox, SandboxList, Shard

from .._shared import env, equal, ok, raw
from .harness import Check, Context, rejects

# The local routes 488 keeps off serve; a probe that would change the daemon goes last, after every other refusal.
LOCAL_PROBES = [
    ("GET", "/v0/daemon"),
    ("GET", "/v0/local/sandboxes"),
    ("GET", "/v0/local/sandboxes/suite-py-no-such-sandbox"),
    ("GET", "/v0/images"),
    ("DELETE", "/v0/images/suite-py-no-such-image:none"),
    ("POST", "/v0/images/pull"),
    ("POST", "/v0/images/prune"),
]

# A scoped key is refused a local route on main too, so only a "*" key proves serve keeps the route local.
WILDCARD_KEY_ENV = "SHARD_SUITE_WILDCARD_KEY"


def listed(remote: str | None = None, api_key: str | None = None) -> SandboxList[Sandbox]:
    with Shard(remote=remote, api_key=api_key) as shard:
        return shard.list()


def env_defaults(ctx: Context) -> None:
    ok(isinstance(listed(), SandboxList), "a client from SHARD_REMOTE and SHARD_API_KEY lists sandboxes")


def explicit_overrides(ctx: Context) -> None:
    remote = os.environ.get("SHARD_REMOTE")
    api_key = os.environ.get("SHARD_API_KEY")
    with env(SHARD_REMOTE="https://shard.invalid", SHARD_API_KEY="shard_not_a_key"):
        ok(isinstance(listed(remote, api_key), SandboxList), "explicit settings win over bad env")
    rejects(AuthenticationError, lambda: listed(api_key="shard_not_a_key"))


def no_key(ctx: Context) -> None:
    with env(SHARD_API_KEY=None):
        rejects(ConfigurationError, listed)


def bad_key(ctx: Context) -> None:
    err = rejects(AuthenticationError, lambda: listed(api_key="shard_not_a_key"))
    equal(err.status, 401)


def local_routes_refused(ctx: Context) -> None:
    wildcard = os.environ.get(WILDCARD_KEY_ENV)
    if not wildcard:
        raise AssertionError(f'{WILDCARD_KEY_ENV} is not set: it must hold a "*" token')
    keys = [("SHARD_API_KEY", os.environ.get("SHARD_API_KEY", "")), (WILDCARD_KEY_ENV, wildcard)]
    refusal: str | None = None
    for method, path in LOCAL_PROBES:
        for name, key in keys:
            got = raw(method, path, key)
            equal(got.status, 403, f"{method} {path} with {name} answered {got.body!r}")
            # Every local route reads like an unknown one, so the body is the same for all of them.
            refusal = got.body if refusal is None else refusal
            equal(got.body, refusal, f"{method} {path} with {name} answered a different refusal")
    unknown = raw("GET", "/v0/suite-py-no-such-route")
    equal(unknown.status, 403)
    equal(unknown.body, refusal, "a local route is refused like an unknown route")


def version_public(ctx: Context) -> None:
    version = ctx.shard.version()
    ok(len(version.version) > 0, "version names the daemon version")
    got = raw("GET", "/v0/version")
    equal(got.status, 200)
    keys = sorted(set(json.loads(got.body)) - {"version", "api_version"})
    equal(keys, [], "the public version holds nothing but versions")


CHECKS = [
    Check("auth.env_defaults", env_defaults),
    Check("auth.explicit_overrides", explicit_overrides),
    Check("auth.no_key", no_key),
    Check("auth.bad_key", bad_key),
    Check("auth.local_routes_refused", local_routes_refused),
    Check("auth.version_public", version_public),
]
