# Generated by scripts/unasync.py from suite/_async/commands.py. Edit that file, not this one.
from __future__ import annotations

from useshards import Command, CommandNotStartedError, TerminalSize

from .._shared import equal, matches, ok
from .harness import Check, Context, rejects, wait_for
from .mode import Printed, cancel_after


def state(command: Command) -> str:
    return (command.inspect()).state


def argv(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    result = sandbox.exec(["printf", "%s", "hello world"])
    equal(result.exit_code, 0)
    equal(result.stdout, "hello world", "a list runs as argv, with no shell to split it")
    equal(result.stderr, "")


def shell(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    result = sandbox.exec("printf '%s' hello; echo oops >&2; echo $((1 + 2))")
    equal(result.exit_code, 0)
    equal(result.stdout, "hello3\n", "a string runs under /bin/sh -c")
    equal(result.stderr, "oops\n")


def env_workdir_user(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    result = sandbox.exec('echo "$GREETING"; pwd; id -u', env={"GREETING": "hi there"}, workdir="/tmp", user="nobody")
    equal(result.stdout, "hi there\n/tmp\n65534\n")


def stdin(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    equal((sandbox.exec(["cat"], stdin="from a string\n")).stdout, "from a string\n")
    result = sandbox.exec("od -An -tu1", stdin=bytes([0, 1, 2, 250, 255]))
    equal(",".join(result.stdout.split()), "0,1,2,250,255", "stdin carries bytes as they are")
    open_ = sandbox.exec(["cat"], background=True, stdin=True)
    open_.write_stdin("first ")
    open_.write_stdin(b"second")
    open_.close_stdin()
    equal((open_.wait()).stdout, "first second", "close ends the input, so cat ends")


def tty_resize(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    first = Printed("24 80")
    command = sandbox.exec(
        "stty size; read line; stty size",
        background=True,
        stdin=True,
        tty=TerminalSize(rows=24, cols=80),
        on_stdout=first.on_stdout,
    )
    first.seen()
    command.resize(40, 120)
    command.write_stdin("\n")
    result = command.wait()
    equal(result.exit_code, 0)
    matches(result.stdout, r"24 80\r?\n[\s\S]*40 120", "the second stty sees the new size")
    equal(result.stderr, "", "a terminal sends everything as stdout")


def nonzero_result(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    result = sandbox.exec("echo partial; exit 3")
    equal(result.exit_code, 3, "a nonzero exit is a result, not an error")
    equal(result.stdout, "partial\n")
    equal((sandbox.exec(["false"])).exit_code, 1)


def not_started_named(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    err = rejects(CommandNotStartedError, lambda: sandbox.exec(["/no/such/binary"]))
    equal(err.exit_code, 127)
    matches(err.reason, r"no/such/binary")
    result = sandbox.exec("/no/such/binary")
    equal(result.exit_code, 127, "the shell started, so a missing binary under it is a result")


def background_wait_kill(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    quick = sandbox.exec("sleep 1; echo done", background=True)
    ok(len(quick.id) > 0, "a background command has an id once it started")
    result = quick.wait()
    equal(result.exit_code, 0)
    equal(result.stdout, "done\n")
    long = sandbox.exec(["sleep", "300"], background=True)
    equal(state(long), "running")
    long.kill()
    # The exit is the code alone, 128 plus the signal, on every provider (SHARD-432).
    termed = long.wait()
    equal((termed.exit_code, termed.signal), (143, None), "kill sends TERM by default")
    hard = sandbox.exec(["sleep", "300"], background=True)
    hard.kill("KILL")
    killed = hard.wait()
    equal((killed.exit_code, killed.signal), (137, None))


def list_get(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    command = sandbox.exec(["sleep", "300"], background=True)
    entry = next((each for each in sandbox.commands.list() if each.id == command.id), None)
    if entry is None:
        raise AssertionError("list holds the running command")
    equal(entry.command, ("sleep", "300"))
    equal(entry.state, "running")
    got = sandbox.commands.get(command.id)
    equal(got.id, command.id)
    equal(state(got), "running")
    got.kill()

    def exited() -> bool:
        return state(command) == "exited"

    wait_for("the killed command to end", 10, exited)
    ended = next((each for each in sandbox.commands.list() if each.id == command.id), None)
    if ended is None:
        raise AssertionError("list still holds the killed command")
    equal((ended.exit_code, ended.signal), (143, None))


def reconnect(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    one = Printed("one")
    command = sandbox.exec("echo one; sleep 2; echo two", background=True, on_stdout=one.on_stdout)
    one.seen()
    command.disconnect()
    command.reconnect()
    result = command.wait()
    equal(result.exit_code, 0)
    equal(result.stdout, "one\ntwo\n", "a reconnect replays what the daemon holds, then streams the rest")


def disconnect(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    marker = ctx.name("disconnect")
    command = sandbox.exec(f"sleep 2; echo {marker} > /tmp/{marker}", background=True)
    command.disconnect()
    equal(state(command), "running", "a disconnect leaves the command running")

    def exited() -> bool:
        return state(command) == "exited"

    wait_for("the disconnected command to end", 15, exited)
    equal(sandbox.files.read_text(f"/tmp/{marker}"), f"{marker}\n")


def cancel_keeps_remote(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    marker = ctx.name("cancel")
    cancel_after(
        lambda on_stdout: sandbox.exec(f"echo started; sleep 3; echo {marker} > /tmp/{marker}", on_stdout=on_stdout),
        "started",
    )
    # A second client, as another process would make one, finds the command still running.
    other = ctx.client().get(sandbox.id)
    entry = next((each for each in other.commands.list() if marker in " ".join(each.command)), None)
    if entry is None:
        raise AssertionError("the second client lists the cancelled command")
    equal(entry.state, "running", "a client cancel leaves the remote command running")
    result = (other.commands.get(entry.id)).wait()
    equal(result.exit_code, 0)
    equal(result.stdout, "started\n")
    equal(other.files.read_text(f"/tmp/{marker}"), f"{marker}\n")


CHECKS = [
    Check("commands.argv", argv),
    Check("commands.shell", shell),
    Check("commands.env_workdir_user", env_workdir_user),
    Check("commands.stdin", stdin),
    Check("commands.tty_resize", tty_resize),
    Check("commands.nonzero_result", nonzero_result),
    Check("commands.not_started_named", not_started_named),
    Check("commands.background_wait_kill", background_wait_kill),
    Check("commands.list_get", list_get),
    Check("commands.reconnect", reconnect),
    Check("commands.disconnect", disconnect),
    Check("commands.cancel_keeps_remote", cancel_keeps_remote),
]
