# Generated by scripts/unasync.py from suite/_async/files.py. Edit that file, not this one.
from __future__ import annotations

import os
from pathlib import Path

from useshards import NotFoundError

from .._shared import MiB, equal, local_dir, ok, read_local, remove_local, tree, write_local
from .harness import Check, Context, rejects


def scratch(ctx: Context) -> Path:
    """A local temp dir the check's cleanup removes."""
    path = local_dir(ctx.prefix)

    def remove() -> None:
        remove_local(path)

    ctx.defer(f"remove {path}", remove)
    return path


def write_read(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    folder = f"/tmp/{ctx.name('files')}"
    sandbox.files.mkdir(folder)
    sandbox.files.write(f"{folder}/hello.txt", "hello files\n")
    equal(sandbox.files.read_text(f"{folder}/hello.txt"), "hello files\n")
    equal((sandbox.exec(["cat", f"{folder}/hello.txt"])).stdout, "hello files\n", "the guest sees the write")
    data = os.urandom(3 * MiB)
    sandbox.files.write(f"{folder}/blob", data)
    ok(sandbox.files.read(f"{folder}/blob") == data, "bytes round-trip unchanged")
    rejects(NotFoundError, lambda: sandbox.files.read(f"{folder}/missing"))


def metadata(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    folder = f"/tmp/{ctx.name('meta')}"
    sandbox.files.mkdir(folder)
    sandbox.files.write(f"{folder}/script.sh", "#!/bin/sh\necho hi\n", mode=0o750)
    info = sandbox.files.stat(f"{folder}/script.sh")
    equal(info.type, "file")
    equal(info.size, 18)
    equal(info.mode, 0o750)
    ok(info.mtime.tzinfo is not None, f"mtime {info.mtime} carries its zone")
    equal((sandbox.exec([f"{folder}/script.sh"])).stdout, "hi\n", "the mode reaches the guest")
    equal((sandbox.files.stat(folder)).type, "dir")
    rejects(NotFoundError, lambda: sandbox.files.stat(f"{folder}/missing"))


def list_mkdir_remove(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    folder = f"/tmp/{ctx.name('tree')}"
    sandbox.files.mkdir(f"{folder}/a/b", parents=True)
    sandbox.files.write(f"{folder}/a/one.txt", "1")
    names = sorted(f"{entry.name}:{entry.type}" for entry in sandbox.files.list(f"{folder}/a"))
    equal(names, ["b:dir", "one.txt:file"])
    sandbox.files.remove(f"{folder}/a/one.txt")
    rejects(NotFoundError, lambda: sandbox.files.stat(f"{folder}/a/one.txt"))
    sandbox.files.remove(folder, recursive=True)
    rejects(NotFoundError, lambda: sandbox.files.list(folder))


def file_transfer(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    local = scratch(ctx)
    data = os.urandom(5 * MiB)
    write_local(local / "up.bin", data)
    remote = f"/tmp/{ctx.name('transfer')}.bin"
    sandbox.files.upload(local / "up.bin", remote)
    equal((sandbox.files.stat(remote)).size, len(data))
    sandbox.files.download(remote, local / "down.bin")
    ok(read_local(local / "down.bin") == data, "a file transfer round-trips every byte")


def dir_transfer(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    local = scratch(ctx)
    source = local / "source"
    write_local(source / "top.txt", b"top\n")
    write_local(source / "nested" / "mid.bin", os.urandom(MiB))
    write_local(source / "nested" / "deeper" / "leaf.txt", b"leaf\n")
    write_local(source / "nested" / "empty", b"")
    remote = f"/tmp/{ctx.name('dir')}"
    sandbox.files.upload_dir(source, remote)
    equal(sandbox.files.read_text(f"{remote}/nested/deeper/leaf.txt"), "leaf\n")
    back = local / "back"
    sandbox.files.download_dir(remote, back)
    want = tree(source)
    got = tree(back)
    equal(sorted(got), sorted(want), "the same files come back")
    for path, data in want.items():
        ok(got.get(path) == data, f"{path} came back changed")
    ok((back / "nested" / "deeper").is_dir(), "the nested directory comes back")


CHECKS = [
    Check("files.write_read", write_read),
    Check("files.metadata", metadata),
    Check("files.list_mkdir_remove", list_mkdir_remove),
    Check("files.file_transfer", file_transfer),
    Check("files.dir_transfer", dir_transfer),
]
