# Generated by scripts/unasync.py from suite/_async/lifecycle.py. Edit that file, not this one.
from __future__ import annotations

import re

import attrs

from useshards import ConflictError, NotFoundError, Sandbox, UnsupportedError

from .._shared import equal, matches, named, not_equal, ok, skip
from .harness import Check, Context, rejects
from .mode import Call

INIT = re.compile(r"^(\S*/)?(shard-)?init\b")


def others(sandbox: Sandbox) -> list[str]:
    """The guest processes besides init and the ps that lists them."""
    result = sandbox.exec(["ps", "-o", "args"])
    equal(result.exit_code, 0, result.stderr)
    # Kernel threads print in brackets on a microVM, and a container has none.
    return [
        line
        for line in result.stdout.split("\n")[1:]
        if line and not line.startswith("[") and line != "ps -o args" and not INIT.match(line)
    ]


def create_no_app(ctx: Context) -> None:
    sandbox = ctx.create(env={"MODE": "test"}, memory_mib=256)
    equal(sandbox.info.state, "running")
    equal(sandbox.info.resources.memory_mib, 256)
    equal(sandbox.info.app, None, "create starts no app")
    equal((sandbox.exec("printenv MODE")).stdout, "test\n")
    equal(others(sandbox), [], "only init and the exec itself run in a sandbox with no app")


def inspect_get_list(ctx: Context) -> None:
    sandbox = ctx.sandbox()
    info = sandbox.inspect()
    equal(info.id, sandbox.id)
    equal(info.state, "running")
    ok(info.image.endswith(ctx.image), f"image {info.image}")
    equal((ctx.shard.get(sandbox.id)).id, sandbox.id)
    equal((ctx.shard.get(named(sandbox.name, "the sandbox"))).id, sandbox.id)
    ok(any(each.id == sandbox.id for each in (ctx.shard.list()).sandboxes), "list holds the sandbox")
    rejects(NotFoundError, lambda: ctx.shard.get(f"{ctx.prefix}-no-such-sandbox"))


def stop_start(ctx: Context) -> None:
    sandbox = ctx.create()
    sandbox.exec("echo kept > /root/kept")
    sandbox.stop()
    equal((sandbox.inspect()).state, "stopped")
    rejects(ConflictError, lambda: sandbox.exec("true"))
    sandbox.start()
    equal((sandbox.inspect()).state, "running")
    equal((sandbox.exec("cat /root/kept")).stdout, "kept\n", "a start keeps the root a stop left")


def pause_resume(ctx: Context) -> None:
    sandbox = ctx.create()
    sandbox.exec("echo before > /root/before")
    try:
        sandbox.pause()
    except UnsupportedError as e:
        raise skip(f"the provider has no pause: {e.message}") from None
    equal((sandbox.inspect()).state, "paused")
    rejects(ConflictError, lambda: sandbox.exec("true"))
    sandbox.resume()
    equal((sandbox.inspect()).state, "running")
    equal((sandbox.exec("cat /root/before")).stdout, "before\n")


def fork(ctx: Context) -> None:
    source = ctx.create()
    source.exec("echo source > /root/origin")
    try:
        forked = source.fork(name=ctx.name("fork"))
    except UnsupportedError as e:
        raise skip(f"the provider has no fork: {e.message}") from None
    ctx.defer(f"remove sandbox {forked.id}", lambda: forked.remove(force=True))
    not_equal(forked.id, source.id)
    equal((forked.inspect()).state, "running")
    equal((forked.exec("cat /root/origin")).stdout, "source\n", "the fork holds the source's files")
    forked.exec("echo fork > /root/origin")
    equal((source.exec("cat /root/origin")).stdout, "source\n", "a write in the fork leaves the source")
    equal((source.inspect()).state, "running", "the source runs on")


def remove(ctx: Context) -> None:
    running = ctx.create()
    rejects(ConflictError, lambda: running.remove())
    running.remove(force=True)
    rejects(NotFoundError, lambda: ctx.shard.get(running.id))
    stopped = ctx.create()
    stopped.stop()
    stopped.remove()
    rejects(NotFoundError, stopped.inspect)


def unsupported_named(ctx: Context) -> None:
    sandbox = ctx.create()

    def pause_then_resume() -> None:
        sandbox.pause()
        sandbox.resume()

    def fork_then_remove() -> None:
        forked = sandbox.fork(name=ctx.name("fork"))
        forked.remove(force=True)

    attempts: list[tuple[str, Call]] = [("pause", pause_then_resume), ("fork", fork_then_remove)]
    refused: list[UnsupportedError] = []
    for verb, attempt in attempts:
        try:
            attempt()
        except UnsupportedError as e:
            matches(e.message, verb, f"the refusal names {verb}")
            refused.append(e)
    if not refused:
        raise skip("the provider runs every optional verb")
    for err in refused:
        equal(err.code, "unsupported")


def agrees(verb: str, supported: bool, run: Call) -> None:
    """Run a verb, and prove the capabilities said whether the server would refuse it."""
    try:
        run()
    except UnsupportedError as e:
        equal(supported, False, f"capabilities say {verb}, but the server refused it: {e.message}")
        matches(e.message, verb, f"the refusal names {verb}")
        return
    equal(supported, True, f"capabilities say no {verb}, but it ran")


def capabilities(ctx: Context) -> None:
    verbs = attrs.asdict(ctx.shard.capabilities())
    equal(sorted(verbs), ["create", "fork", "pause", "remove", "resume", "snapshot", "start", "stop"])
    ok(all(isinstance(value, bool) for value in verbs.values()), f"every verb is a boolean: {verbs}")
    for verb in ("create", "start", "stop", "remove"):
        equal(verbs[verb], True, f"every provider can {verb}")
    equal(verbs["resume"], verbs["pause"], "pause and resume come as a pair")
    sandbox = ctx.create()

    def pause_then_resume() -> None:
        sandbox.pause()
        sandbox.resume()

    def fork_then_remove() -> None:
        forked = sandbox.fork(name=ctx.name("fork"))
        forked.remove(force=True)

    def snapshot() -> None:
        ctx.snapshot(sandbox)

    agrees("pause", verbs["pause"], pause_then_resume)
    agrees("fork", verbs["fork"], fork_then_remove)
    sandbox.stop()
    agrees("snapshot", verbs["snapshot"], snapshot)


CHECKS = [
    Check("lifecycle.create_no_app", create_no_app),
    Check("lifecycle.inspect_get_list", inspect_get_list),
    Check("lifecycle.stop_start", stop_start),
    Check("lifecycle.pause_resume", pause_resume),
    Check("lifecycle.fork", fork),
    Check("lifecycle.remove", remove),
    Check("lifecycle.unsupported_named", unsupported_named),
    Check("lifecycle.capabilities", capabilities),
]
