# Generated by scripts/unasync.py from suite/_async/logs.py. Edit that file, not this one.
from __future__ import annotations

from useshards import EgressDecision, PolicyRule, Sandbox

from .._shared import equal, matches, not_equal, ok
from .harness import Check, Context, wait_for
from .mode import Cancelled, consume


def denied(ctx: Context) -> Sandbox:
    """A running sandbox under a policy that denies everything, so any request it makes leaves a deny record."""
    policy = ctx.name("deny")
    ctx.policy(policy, [PolicyRule(action="deny", rule="any")])
    return ctx.create(policy=policy)


def request(sandbox: Sandbox, host: str) -> None:
    result = sandbox.exec(f"wget -q -T 5 -O /dev/null http://{host}/")
    not_equal(result.exit_code, 0, f"the policy let {host} through")


def denied_host(records: list[EgressDecision], host: str) -> EgressDecision | None:
    return next((record for record in records if record.verdict == "deny" and record.host == host), None)


def read(ctx: Context) -> None:
    sandbox = ctx.create()
    job = sandbox.run("echo line-one; echo line-two >&2; sleep 300")
    logs = ""

    def both() -> bool:
        nonlocal logs
        logs = job.logs()
        return "line-two\n" in logs

    wait_for("both lines in the logs", 15, both)
    ok("line-one\n" in logs, f"the logs hold stdout: {logs!r}")


def follow(ctx: Context) -> None:
    sandbox = ctx.create()
    job = sandbox.run("for i in 1 2 3; do echo tick $i; sleep 1; done; sleep 300")
    out = b""
    with job.follow_logs() as stream:
        for chunk in stream:
            out += chunk
            if b"tick 3\n" in out:
                break
    matches(out.decode(), r"tick 1\n[\s\S]*tick 2\n[\s\S]*tick 3\n", "the follow yields the lines as they come")

    rest = bytearray()
    ended = consume(job.follow_logs(), rest.extend)

    def replayed() -> bool:
        return b"tick 3\n" in rest

    wait_for("the second follow to replay the log", 10, replayed)
    ok(rest.startswith(b"tick 1\n"), "a follow starts at the beginning of the log")
    sandbox.stop()
    equal(ended.result(), None, "a stop ends the follow without an error")


def egress_read(ctx: Context) -> None:
    sandbox = denied(ctx)
    host = f"{ctx.name('host')}.example"
    request(sandbox, host)
    records: list[EgressDecision] = []

    def recorded() -> bool:
        nonlocal records
        records = sandbox.egress_log()
        return denied_host(records, host) is not None

    wait_for(f"a deny record for {host}", 10, recorded)
    record = denied_host(records, host)
    if record is None:
        raise AssertionError(f"no deny record for {host}")
    ok(record.time.tzinfo is not None, f"time {record.time} carries its zone")
    ok(len(record.rule) > 0, "a record names the rule that decided it")


def egress_follow(ctx: Context) -> None:
    sandbox = denied(ctx)
    host = f"{ctx.name('host')}.example"
    seen: list[EgressDecision] = []
    ended = consume(sandbox.follow_egress_log(), seen.append)
    try:
        request(sandbox, host)

        def recorded() -> bool:
            return denied_host(seen, host) is not None

        wait_for(f"the follow to yield a deny record for {host}", 10, recorded)
    finally:
        ended.cancel()
    ok(isinstance(ended.result(), Cancelled), "a cancel ends the follow and nothing else does")


CHECKS = [
    Check("logs.read", read),
    Check("logs.follow", follow),
    Check("logs.egress_read", egress_read),
    Check("logs.egress_follow", egress_follow),
]
