# Generated by scripts/unasync.py from suite/_async/policies.py. Edit that file, not this one.
from __future__ import annotations

from useshards import ConflictError, InvalidRequestError, NotFoundError, PolicyRule

from .._shared import equal, ok
from .harness import Check, Context, rejects

# Each rule is spelled as the daemon spells it back, so a round trip compares equal.
RULES = (
    PolicyRule(action="allow", rule="suffix:example.com tcp:443"),
    PolicyRule(action="allow", rule="10.0.0.0/8 tcp:22"),
    PolicyRule(action="deny", rule="any"),
)


def set_get_list_remove(ctx: Context) -> None:
    name = ctx.name("policy")
    made = ctx.policy(name, RULES)
    equal(made.name, name)
    equal(made.rules, RULES)
    equal((ctx.shard.policies.get(name)).rules, RULES, "the rules come back in order")
    ok(any(each.name == name for each in ctx.shard.policies.list()), "list holds the policy")
    replaced = (PolicyRule(action="deny", rule="any"),)
    ctx.shard.policies.set(name, replaced)
    equal((ctx.shard.policies.get(name)).rules, replaced, "a set replaces every rule")
    bad = [PolicyRule(action="allow", rule="not a rule at all")]
    rejects(InvalidRequestError, lambda: ctx.shard.policies.set(ctx.name("bad"), bad))
    ctx.shard.policies.remove(name)
    rejects(NotFoundError, lambda: ctx.shard.policies.get(name))


def attach_detach(ctx: Context) -> None:
    name = ctx.name("policy")
    ctx.policy(name, RULES)
    sandbox = ctx.create()
    equal(sandbox.info.policy, None)
    rejects(ConflictError, lambda: ctx.shard.policies.attach(sandbox, name))
    sandbox.stop()
    ctx.shard.policies.attach(sandbox, name)
    equal((sandbox.inspect()).policy, name)
    rejects(ConflictError, lambda: ctx.shard.policies.remove(name))
    ctx.shard.policies.detach(sandbox)
    equal((sandbox.inspect()).policy, None)


CHECKS = [
    Check("policies.set_get_list_remove", set_get_list_remove),
    Check("policies.attach_detach", attach_detach),
]
