# Generated by scripts/unasync.py from suite/_async/secrets.py. Edit that file, not this one.
from __future__ import annotations

import os

from useshards import ConflictError, NotFoundError

from .._shared import equal, ok
from .harness import Check, Context, rejects

DESTINATIONS = ("api.example.com",)


def value() -> str:
    return f"suite-value-{os.urandom(8).hex()}"


def set_list_remove(ctx: Context) -> None:
    name = ctx.variable("secret")
    secret = value()
    ctx.secret(name, secret, DESTINATIONS)
    listed = ctx.shard.secrets.list()
    entry = next((each for each in listed if each.name == name), None)
    if entry is None:
        raise AssertionError("list holds the secret")
    equal(entry.destinations, DESTINATIONS)
    equal(entry.placeholder, f"mock-{name}")
    ok(entry.updated_at.tzinfo is not None, f"updated_at {entry.updated_at} carries its zone")
    ok(secret not in repr(listed), "a list never carries a value")
    ctx.shard.secrets.set(name, value=f"{secret}-rotated", destinations=DESTINATIONS)
    rotated = next((each for each in ctx.shard.secrets.list() if each.name == name), None)
    equal(rotated.placeholder if rotated is not None else None, f"mock-{name}", "a rotation keeps the placeholder")
    ctx.shard.secrets.remove(name)
    ok(all(each.name != name for each in ctx.shard.secrets.list()), "list drops the secret")
    rejects(NotFoundError, lambda: ctx.shard.secrets.remove(name))


def grant_ungrant(ctx: Context) -> None:
    name = ctx.variable("grant")
    secret = value()
    ctx.secret(name, secret, DESTINATIONS)
    sandbox = ctx.create()
    rejects(ConflictError, lambda: ctx.shard.secrets.grant(sandbox, name))
    sandbox.stop()
    ctx.shard.secrets.grant(sandbox, name)
    equal((sandbox.inspect()).secrets, (name,))
    sandbox.start()
    printed = sandbox.exec(f"printenv {name}")
    equal(printed.stdout, f"mock-{name}\n", "the guest holds the placeholder")
    ok(secret not in printed.stdout, "the guest never holds the value")
    rejects(ConflictError, lambda: ctx.shard.secrets.remove(name))
    sandbox.stop()
    ctx.shard.secrets.ungrant(sandbox, name)
    equal((sandbox.inspect()).secrets, ())
    sandbox.start()
    equal((sandbox.exec(f"printenv {name}")).exit_code, 1, "an ungrant takes the placeholder back")
    holder = ctx.create(secrets=[name])
    equal((holder.exec(f"printenv {name}")).stdout, f"mock-{name}\n", "a create grants it too")


CHECKS = [
    Check("secrets.set_list_remove", set_list_remove),
    Check("secrets.grant_ungrant", grant_ungrant),
]
