# Generated by scripts/unasync.py from suite/_async/snapshots.py. Edit that file, not this one.
from __future__ import annotations

from useshards import ConflictError, NotFoundError

from .._shared import equal, named, ok
from .harness import Check, Context, rejects


def needs_stopped(ctx: Context) -> None:
    running = ctx.sandbox()
    rejects(ConflictError, lambda: ctx.shard.snapshots.create(running, name=ctx.name("snapshot")))


def create_list_inspect(ctx: Context) -> None:
    source = ctx.snapshot_source()
    snapshot = ctx.snapshot(source)
    equal(snapshot.source, source.id)
    name = named(snapshot.name, "the snapshot")
    ok(name.startswith(ctx.prefix), f"snapshot name {name}")
    ok(any(each.id == snapshot.id for each in ctx.shard.snapshots.list()), "list holds the snapshot")
    equal((ctx.shard.snapshots.inspect(snapshot.id)).name, snapshot.name)
    equal((ctx.shard.snapshots.inspect(name)).id, snapshot.id)


def create_from(ctx: Context) -> None:
    snapshot = ctx.snapshot(ctx.snapshot_source())
    sandbox = ctx.create(snapshot=snapshot.id)
    equal(sandbox.info.state, "running")
    equal((sandbox.exec("cat /root/marker")).stdout, "snapshot\n", "the new sandbox holds the snapshot's files")


def outlive_source(ctx: Context) -> None:
    source = ctx.stopped_source()
    snapshot = ctx.snapshot(source)
    source.remove()
    rejects(NotFoundError, source.inspect)
    equal((ctx.shard.snapshots.inspect(snapshot.id)).id, snapshot.id, "the snapshot outlives its source")
    sandbox = ctx.create(snapshot=snapshot.id)
    equal((sandbox.exec("cat /root/marker")).stdout, "snapshot\n")


def remove(ctx: Context) -> None:
    snapshot = ctx.snapshot(ctx.snapshot_source())
    ctx.shard.snapshots.remove(snapshot.id)
    rejects(NotFoundError, lambda: ctx.shard.snapshots.inspect(snapshot.id))
    ok(all(each.id != snapshot.id for each in ctx.shard.snapshots.list()), "list drops the snapshot")


CHECKS = [
    Check("snapshots.needs_stopped", needs_stopped),
    Check("snapshots.create_list_inspect", create_list_inspect),
    Check("snapshots.create_from", create_from),
    Check("snapshots.outlive_source", outlive_source),
    Check("snapshots.remove", remove),
]
