// Writes the private types of the public API from the committed spec; `make sdk-ts` runs it and CI fails on drift.
import fs from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const spec = new URL("../../../docs/openapi.json", import.meta.url);
const out = new URL("../src/generated/schema.ts", import.meta.url);
const ast = await openapiTS(spec, {
  transform(schema) {
    if (schema.format === "binary") {
      return ts.factory.createTypeReferenceNode("Blob");
    }
  },
});
await fs.mkdir(new URL(".", out), { recursive: true });
await fs.writeFile(out, `// Generated by scripts/generate.mjs from docs/openapi.json; \`make sdk-ts\` rewrites it.\n${astToString(ast)}`);
