# logfilename                [owner:group]   mode count size(KB) when flags pid_file                   sig_num
/var/log/shard/daemon.log    __USER__:staff  600  7     10240    *    -     /var/lib/shard/daemon.pid  1
